switch to standard X-Forwarded-Proto instead of X-Forwarded-Protocol
silverstripe/silverstripe-framework pull request #10018
Opened 2021-07-08 22:02 UTC by xini

Silverstripe currently uses the non-standard X-Forwarded-Protocol header. This PR changes that to X-Forwarded-Proto.

See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto.

2021-07-09 10:25 UTC, dhensby commented
Note that this is a "defacto-standard" it is not a standard (any headers that start `X-*` are non-standardised headers).

If we wanted to make this change, I think it would have to be in a way that maintained support for `X-Forwarded-Protocol`

2021-07-09 10:26 UTC, dhensby requested changes
we need to maintain support for the existing headers

2021-07-13 01:54 UTC, xini commented
No problem. Where would you want to keep both?

2021-07-13 02:54 UTC, michalkleiner commented
For systems that rely on the X-Forwarded-Protocol (despite it being custom and non-standard), where changing the name of the header in a patch or minor version could cause unexpected behaviour. So it's basically about semver.

2022-07-07 01:33 UTC, GuySartorelli commented
Note: The documentation portion should not be merged here. I have started [the process of migrating docs](https://github.com/silverstripe/silverstripe-framework/issues/10215) to [a new repository](https://github.com/silverstripe/doc) so the docs will need to be removed from this PR and a new PR raised in the new repo instead.

2023-12-20 03:35 UTC, GuySartorelli commented
@xini This has been laying dormant for a while. Do you still want to work on this to get it merged? Or would you rather we close this now?

2023-12-20 03:38 UTC, xini commented
This should have gone into SS 5.0. Now we have to wait for SS 6. right?

2023-12-20 03:42 UTC, GuySartorelli commented
No - as per the comments above, we could support both headers together. In that case, please retarget to the `5` branch.

If you want to explicitly swap from using one header to using the other, then yes it will need to wait for Silverstripe CMS 6. In that case, we should close this PR and you can reopen it when there's a branch for it to target.

2023-12-21 22:07 UTC, GuySartorelli commented
I'll assume for now that you don't want to introduce support for both headers at the same time (that would be probably fairly complicated for minimal benefit) - so I'll close the PR. Please feel free to raise a new PR for CMS 6 once branches for that have been created early next year.

2023-12-21 22:07 UTC, closed without merging

2023-12-21 22:49 UTC, xini commented
Thanks. I have created an issue to track this. Can you mark that for SS6?