take current request protocol into account when deleting session cookie
silverstripe/silverstripe-framework pull request #10022
Opened 2021-07-13 01:53 UTC by xini

Check whether the request was actually using HTTPS or not. 

In `Session::start()` this is checked the same way. If this is not checked when deleting the cookie, the cookie doesn't match the created one and is not deleted.

2021-07-16 09:32 UTC, dhensby requested changes
This is a breaking API change, the request Param will have to be last and optional in the signature.

You need to update the PHP docblock.

Please target the 4 branch and not 4.8 as this is a new feature.

2021-07-20 01:52 UTC, xini commented
I have amended the order of the parameters to match the old behavior.

Are you sure you want me to rebase this to 4 though? This is a bugfix to make sure a cookie is removed in case a request was through http, even if `cookie_secure` is set to true. I don't see how this is new functionality.

2021-07-20 14:45 UTC, dhensby commented
This changes an function signature which I usually class as "new feature", whilst this could be argued it's a bug fix, there's an api change to introduce something new.

Other's can decide if they'd like to take it into a patch release.

I note that once this is merged and finds its way into `4` there will need to be a change to the session destroy call in logout to include this new param (see https://github.com/silverstripe/silverstripe-framework/pull/10023)

2021-07-20 14:45 UTC, dhensby requested changes
The docblock still needs updating

2021-07-20 23:35 UTC, xini commented
@dhensby I have rebased it to 4 and added the changes. Thanks.

2021-07-21 12:48 UTC, dhensby approved these changes

2021-08-05 22:37 UTC, emteknetnz commented
There's something weird with this one in travis where it's still trying to build against the `4.8` recipe in travis.  I've tried manually restarting the build in travis but it keeps the same config

@xini could you please try the following for force a new build in travis with the correct travis config:
```
git reset HEAD~1
git add .
git commit -m 'FIX Take current request protocol into account when deleting session cookie'
git push -f
```

2021-08-06 03:40 UTC, xini commented
@emteknetnz done. thanks!

2021-08-06 09:06 UTC, merged