DOC Surpress deprecation warnings on php7.4
silverstripe/silverstripe-framework pull request #10043
Opened 2021-08-05 00:51 UTC by emteknetnz

Issue https://github.com/silverstripeltd/product-issues/issues/437

2021-08-08 21:52 UTC, dhensby approved these changes

2021-08-12 22:21 UTC, maxime-rainville requested changes
Should use the `[warning]` syntax.

2021-08-12 22:21 UTC, maxime-rainville commented on docs/en/00_Getting_Started/00_Server_Requirements.md
> +```
```suggestion
[warning]
Running CMS3 with PHP 7.4 triggers a number of deprecation warnings.
It's highly recommended you disable deprecation warnings.
For example, you can add the following to the bottom of your `_ss_environment.php` file:
`error_reporting(E_ALL & ~E_DEPRECATED);`

Read the [`error_reporting` PHP documentation](https://www.php.net/manual/en/function.error-reporting.php)
[/warning]
```

2021-08-12 23:55 UTC, emteknetnz commented on docs/en/00_Getting_Started/00_Server_Requirements.md
> +```
Updated

2021-08-17 05:17 UTC, maxime-rainville approved these changes

2021-08-17 05:18 UTC, merged