MNT Skip tests when session-manager module is installed
silverstripe/silverstripe-framework pull request #10073
Opened 2021-08-23 23:42 UTC by emteknetnz

Issue https://github.com/silverstripe/recipe-cms/issues/47

2021-08-24 22:36 UTC, maxime-rainville requested changes
I'm only happy with skipping these tests altogether if they become non-sensical to run when session-manager is installed.

2021-08-24 22:36 UTC, maxime-rainville commented on tests/php/Security/MemberTest.php
> +        if (!class_exists(LoginSession::class)) {
Is the behaviour when session manager installed predictable? Maybe we want to add an opposing test here or in session manager.

2021-08-24 22:36 UTC, maxime-rainville commented on tests/php/Security/RememberLoginHashTest.php
> +        if (class_exists(LoginSession::class)) {
What's the expected behaviour if Session-Manager is installed?

2021-08-24 22:36 UTC, maxime-rainville commented on tests/php/Security/RememberLoginHashTest.php
> +        if (class_exists(LoginSession::class)) {
What's the expected behaviour if Session-Manager is installed?

2021-08-25 00:02 UTC, emteknetnz commented
@maxime-rainville these tests are non-nonsensical IMO when session-manager is installed, because of this line in the session-manager middleware

`RememberLoginHash::setLogoutAcrossDevices(false);`
https://github.com/silverstripe/silverstripe-session-manager/blob/1/src/Middleware/LoginSessionMiddleware.php#L39

The tests are explicitly modifying `logout_across_devices` and then running an assertion.  However session-manager will just override what the test set `logout_across_devices` to

2021-09-02 22:08 UTC, maxime-rainville approved these changes
Just need to fix that rogue comma

2021-09-02 22:08 UTC, maxime-rainville commented on tests/php/Security/MemberTest.php
>              RememberLoginHash::get()->filter(['MemberID'=>$m1->ID, 'DeviceID'=>$firstHash->DeviceID])->count(),
```suggestion
            RememberLoginHash::get()->filter(['MemberID'=>$m1->ID, 'DeviceID'=>$firstHash->DeviceID])->count()
```

2021-09-02 23:11 UTC, maxime-rainville commented
I fixed the comma and updated the build to run recipe-cms 4.9.x just to keep this moving.

2021-09-03 00:20 UTC, merged