Add a basic ContentLocale method to controller
silverstripe/silverstripe-framework pull request #10081
Opened 2021-09-01 10:36 UTC by TheBnl

Add a basic ContentLocale method to controller that doesn't check a dataRecord.

2021-09-02 21:24 UTC, michalkleiner commented on src/Control/Controller.php
> +     * attributes in HTML or XHTML output.
```suggestion
     * Note: The method is overloaded in {@link ContentController} where it takes into account
     * the current data record (@link SiteTree) and adds support for {@link Translatable}.
```

2021-09-04 06:52 UTC, emteknetnz requested changes
I don't think Controller.php is really intended to serve content, that's what ContentController.php is for.


Reading through the issue, `login-forms` is a bit of a special case

I'm thinking a better approach would be to add the `ContentLocale()` method you've created and add it to https://github.com/silverstripe/silverstripe-login-forms/blob/4/src/EnablerExtension.php which is applied to Security.php

2021-09-04 08:19 UTC, michalkleiner commented
@TheBnl I've moved the issue to the login-forms module and I'll close this issue here.
Can you please create a new PR there with the method added to the EnablerExtension as @emteknetnz suggests? Thanks!

2021-09-04 08:19 UTC, closed without merging

2021-09-04 08:20 UTC, michalkleiner commented
Moved issue — https://github.com/silverstripe/silverstripe-login-forms/issues/100