BUG: Datetime now() should be immutable
silverstripe/silverstripe-framework pull request #10125
Opened 2021-10-20 22:24 UTC by mfendeksilverstripe

# BUG: Datetime now() should be immutable

I noticed that `DBDate::now()->modify()` doesn't return a new field instance. This can cause an unintended side-effects and waste time of developers figuring out what the issue is.

This change-set ensures that the `now()` returns an immutable field instance so any existing references to the old field are still pointing to the old value.

I included a unit test to showcase this behaviour.

## Notes

Unit tests failure is an upstream issue not related to this change-set.

## Related issues

https://github.com/silverstripe/silverstripe-framework/issues/10126

2021-10-21 08:32 UTC, kinglozzer commented
I’ve experienced this (one project is littered with `$now = clone DBDateTime::now()`!) but still I’m not sure this change makes sense because `DBField` instances aren’t immutable like, say, `DataList` is, so it feels weird to apply that behaviour to only one method. This method is essentially a shortcut for `->setValue()` which definitely shouldn’t return a new instance of the object. This would also be a BC break for anyone relying on the current behaviour, e.g:

```php
public function onBeforeWrite()
{
    parent::onBeforeWrite();
    $this->dbObject('Expiry')->modify('+1 month');
}
```

2022-01-17 01:55 UTC, emteknetnz requested changes
I'm just really not sure about the semantics this PR is changing

Looking at this line in the DatetimeFieldTest.php

`$later = $now->modify('+ 10 days')->Rfc2822();`

Let's say instead of that, you just had this in the code

`$now->modify('+ 10 days');`

I'd expect `$now->modify('+ 10 days')` modify the `$now` variable.  With this PR `$now` is will be unchanged.  This is backwards to me.

It also means there's a decent chance this will break some sites, so I can't really see how we can merge this in its current state.

I do think it would be better if things were immutable across the board, but the fact is they're not.  I'd rather have things inconsistently not immutable then everything except one particular thing immutable.

2022-01-17 03:17 UTC, mfendeksilverstripe commented
I see where you're coming from @emteknetnz but I still think current behaviour is a bit tricky to use across the board (feature code and unit tests). As far as I can see we have two main scenarios:

1. modify the global state of now
2. get a locale copy of now and modify that

I get the backwards compatibility argument so would you be ok with the following approach?

* keep the current API / behaviour as is (`now()`)
* add a new method (for example `nowImmutable()`) which would return a clone of the Data field

This way we can cover both scenarios and the change is backwards compatible. The developer can choose which method to use on case by case basis.

2022-01-17 03:28 UTC, emteknetnz commented
Would it work if we keep all code change you've made except for the now() method?

Going back to the example given in the description, you'd use the following code:

`DBDate::now()->setImmutable(true)->modify();`

It's a bit verbose and requires an 'opt-in' on each call to now(), though it's backwards compatible.  I think this is slightly better than adding a new `nowImmutable()` method which would do the same thing.  There's probably other use cases for the new `setImmutable()` method you've added here too

Is that acceptable?

2022-01-17 03:45 UTC, mfendeksilverstripe commented
I think you would actually need to do more than that @emteknetnz . Here is a code snippet that you would need to use for the scenario where you don't want to alter the global state at all:

```php
$now = DBDate::now()->setImmutable(true); // This alters the global state in case a mock is set
$now->modify()...// do your modifications here - this is not reflected on the global state
$now->setImmutable(false); // set the global state back to what it was before so we don't alter the global state
```

Still feels like a very roundabout way how to do it. My aim is to provide a simple API.

2022-01-17 03:52 UTC, emteknetnz commented
I might be misunderstanding this, though because `protected $immutable = false;` is non-static, you don't need to change it back via `$now->setImmutable(false);` ?

2022-01-17 03:58 UTC, mfendeksilverstripe commented
Ah yes, you're right @emteknetnz , I think your approach covers my goal well 👍 . I'll push up new changes soon.

2022-01-17 04:16 UTC, mfendeksilverstripe commented
@emteknetnz I've pushed up new changes as requested, please review.

2022-01-17 04:17 UTC, emteknetnz approved these changes
Merge on green

2022-01-17 20:17 UTC, michalkleiner commented
Thanks @mfendeksilverstripe for the contribution. Can you please squash the 'PR fixes' commits into the first one?

2022-01-17 20:41 UTC, merged

2022-01-17 20:41 UTC, emteknetnz commented
@michalkleiner there's no need, I usually use the "Squash and merge" button when merging

2022-01-17 21:23 UTC, michalkleiner commented
@emteknetnz slacked you about that.