DOC Document how to enable the preview panel for custom DataObjects.
silverstripe/silverstripe-framework pull request #10124
Opened 2021-10-20 05:13 UTC by GuySartorelli

Documentation for enabling the preview panel for custom `DataObject`s.

Depends on the other pull requests that are listed in silverstripe/silverstripe-admin#1251. If any of those pull requests change in a material way, this documentation will need to be updated.

2022-01-31 01:28 UTC, emteknetnz commented
@GuySartorelli is this ready for review?

2022-01-31 02:27 UTC, GuySartorelli commented
> @GuySartorelli is this ready for review?

Not yet. It's got some code examples of how to make a `DataObject` previewable under various circumstances, but I want to add a few words around the code to provide context.
I also want to add a small change to the docs at https://userhelp.silverstripe.org/en/4/creating_pages_and_content/creating_and_editing_content/previewing_changes/ to point out the new unversioned preview state.

I'm hoping to get to it this week, but will be done mid next week at the latest. Let me know if that is too slow and I'll see what I can do to move my priorities around.

2022-02-02 00:39 UTC, GuySartorelli commented
@emteknetnz I'm starting to work on this now - do you know where the source for https://userhelp.silverstripe.org/en/4/creating_pages_and_content/creating_and_editing_content/previewing_changes/ is? It doesn't appear to be in the docs folder in this repo.

2022-02-02 01:11 UTC, emteknetnz commented
https://github.com/silverstripe/silverstripe-userhelp-content

2022-02-02 04:05 UTC, GuySartorelli commented
@emteknetnz This is ready for review now. I'll open a PR for the userhelp docs now so that I can link to it from the overarching issue.

I'm not sure that deprecation notice in the javascript is helpful, and if you agree, I'd like to remove it. There's no react replacement for the preview javascript API to my knowledge, so this notice effectively tells developers "You should use the react preview component that doesn't exist instead."

2022-02-03 07:13 UTC, GuySartorelli commented on docs/en/02_Developer_Guides/15_Customising_the_Admin_Interface/04_Preview.md
> +state you can use. This state will always be active one you enable it.
```suggestion
state you can use. This state will always be active once you enable it.
```

2022-02-03 07:14 UTC, GuySartorelli commented on docs/en/02_Developer_Guides/15_Customising_the_Admin_Interface/04_Preview.md
> +It also needs at least one preview state enabled. This example assumed we aren't using
```suggestion
It also needs at least one preview state enabled. This example assumes we aren't using
```

2022-02-03 07:21 UTC, GuySartorelli commented on docs/en/02_Developer_Guides/15_Customising_the_Admin_Interface/04_Preview.md
> +list of items and indirectly calling `forTemplate` using the [`$Me` template variable](../01_Templates/01_Syntax.md#me).
```suggestion
list of items and indirectly calling `forTemplate` using the [`$Me` template variable](../01_Templates/01_Syntax.md#me).
This method will be used by the `MyAdmin` class in the `cmsPreview` action to tell the CMS what to display in the preview panel.
```

2022-02-03 07:24 UTC, GuySartorelli commented on docs/en/02_Developer_Guides/15_Customising_the_Admin_Interface/04_Preview.md
> +edit form would be loaded instead of the `DataObject`'s form. To resolve this, you
```suggestion
edit form would be loaded instead of the `DataObject`'s form. To avoid this unexpected behaviour, you
```

2022-02-03 07:26 UTC, GuySartorelli commented on docs/en/02_Developer_Guides/15_Customising_the_Admin_Interface/04_Preview.md
> +can include an extra GET parameter in the `PreviewLink`. Then in `MetaTags`
```suggestion
can include an extra GET parameter in the `PreviewLink`. Then in the `MetaTags` method,
```

2022-02-03 07:31 UTC, GuySartorelli commented on docs/en/02_Developer_Guides/15_Customising_the_Admin_Interface/04_Preview.md
> + * Used to generated the id for the holder element in the template.
```suggestion
 * Used to generated the id for the product element in the template.
```
Oops, this was a copy/paste error. This concept was taken from the elemental module so there may be a couple other holdovers from that which I missed.

2022-02-03 07:32 UTC, GuySartorelli commented on docs/en/02_Developer_Guides/15_Customising_the_Admin_Interface/04_Preview.md
> +<% loop $Products >
```suggestion
<% loop $Products ‰>
```

2022-02-03 07:34 UTC, GuySartorelli commented
@emteknetnz I decided to read back through it and found a few minor issues I missed while writing it. I'll hold off actually making these changes until you or another core team member has given this a review.

2022-02-03 22:53 UTC, emteknetnz requested changes
Fantastic work.

I've tested the code samples on my local, a few small changes need to be made then we're good to merge

2022-02-03 22:53 UTC, emteknetnz commented on docs/en/02_Developer_Guides/15_Customising_the_Admin_Interface/04_Preview.md
> +        'Page' => Page::class,
```suggestion
        'ProductPage' => ProductPage::class,
```

2022-02-03 22:53 UTC, emteknetnz commented on docs/en/02_Developer_Guides/15_Customising_the_Admin_Interface/04_Preview.md
> +    if ($page = $this->Page()) {
```suggestion
    if ($page = $this->ProductPage()) {
```

2022-02-03 23:39 UTC, GuySartorelli commented on docs/en/02_Developer_Guides/15_Customising_the_Admin_Interface/04_Preview.md
> +valid value. In ~90% of cases will be 'text/html', but note it is also possible to display
Yup I thought that might need to be removed 😅
Might be worth looking at deprecating that method and removing it in 5, but that's out of scope for now.

2022-02-03 23:47 UTC, GuySartorelli commented
@emteknetnz Pretty sure I got all those changes. :)

2022-02-03 23:48 UTC, GuySartorelli commented on docs/en/02_Developer_Guides/15_Customising_the_Admin_Interface/04_Preview.md
> +
Oops, missed the menu title. Will do that now

2022-02-03 23:48 UTC, emteknetnz commented
Still need `private static $menu_title = 'Products';` :-)

2022-02-03 23:50 UTC, emteknetnz approved these changes
Thanks!

2022-02-03 23:50 UTC, merged

2022-02-03 23:57 UTC, GuySartorelli commented
Thank you! It's nice to have this whole thing merged in. 🎉