ENH Provide hook for updating absoluteBaseURL
silverstripe/silverstripe-framework pull request #10168
Opened 2021-12-06 23:11 UTC by GuySartorelli

One use case for this that I've run into a few times is for sending emails using a queued job from the CLI.

Calling `setBody` on an email uses `Director::absoluteURL` which ultimately uses `Director::baseURL` to make email links absolute. This can often result in the host being the server name rather than the actual website host name.

Providing this as an extension makes it easy to configure for a variety of possible situations that could result in needing dynamic control of the absolute base URL - such as using subsites.

2021-12-06 23:50 UTC, michalkleiner commented
It feels wrong adding the same hook/extension point in three different places. Can it be consolidated into one?

2021-12-07 00:13 UTC, GuySartorelli commented
> It feels wrong adding the same hook/extension point in three different places. Can it be consolidated into one?

I didn't want to change too much of the structure of `absoluteURL` - and I think it's important for this the `$parent` to be updatable the same way that the result of `absoluteBaseURL` is updatable.

The only clean ways to consolidate them that I can think of are:
1. Consolidate within `absoluteURL` by moving the hook to just before `$parent` is used, and omit the hook from `absoluteBaseURL` - but then calling `absoluteBaseURL` directly won't have the updated base
2. Move all of the logic that gets different `$parent` values out of `absoluteURL` and into `absoluteBaseURL` while keeping the original _default_ behaviour of `absoluteBaseURL` in tact.

Out of the above I prefer 2 since it means calls to `absoluteBaseURL` have the updated base, but that's a bigger change than I had originally set out to make.

@michalkleiner Let me know if either of the above appeal to you, or if you can think of some alternative that hasn't occurred to me.

2022-01-20 21:31 UTC, emteknetnz commented
Yeah this PR seems a bit wrong in its current state.  We certainly should not have the same hook in 3 different places.

I'm not sure why the 2 hooks in absoluteUrl() are there?

`absoluteBaseURL()` calls `absoluteUrl()`, meaning the hook would get called twice? (once in `absoluteUrl()`, then a second time in `absoluteBaseURL()`)

Seems like we should retain the changes in `absoluteBaseURL()` and revert the `absoluteUrl()`?

2022-01-20 21:32 UTC, emteknetnz requested changes
Yeah this PR seems a bit wrong in its current state. We certainly should not have the same hook in 3 different places.

I'm not sure why the 2 hooks in absoluteUrl() are there?

absoluteBaseURL() calls absoluteUrl(), meaning the hook would get called twice? (once in absoluteUrl(), then a second time in absoluteBaseURL())

Seems like we should retain the changes in absoluteBaseURL() and revert the absoluteUrl()?

2022-01-21 02:45 UTC, GuySartorelli commented
Ultimately, if a developer wants to convert a relative URL to an absolute URL, they will call `absoluteUrl()`, which will use either `self::protocolAndHost()` or `dirname($_SERVER['REQUEST_URI'] . 'x')` as the "base" of the absolute URL. The intention of this PR is to allow developers to define, through an `Extention` class, an alternative "base".

If a developer want just the absolute base URL, it should be likewise updated - but as you correctly pointed out this ultimately will call `absoluteUrl()` anyway so we can remove the call in `absoluteBaseUrl` itself.

I think that having looked at this with fresh eyes the best way to do this is to put a single hook after the `$parent` variable has been determined and pass in that variable to be set. That variable does, afterall, effectively represent _the_ absolute base URL.
https://github.com/silverstripe/silverstripe-framework/blob/f9cceef9b5f4ae72fa60de957c039aa061e0c1f1/src/Control/Director.php#L453-L472

If @emteknetnz and @michalkleiner are happy with this approach, I'll make the change.

2022-01-21 04:15 UTC, emteknetnz commented
Yes, just adding a single extension hook inside `absoluteURL()` `static::singleton()->extend('updateAbsoluteURLParent', $parent);` seems like it should be sufficient

I don't think we need to do anything with the line 456 since that's for external linls

2022-01-31 06:47 UTC, GuySartorelli commented
@emteknetnz I've made the change. That's much nicer, I'm glad you didn't like my first approach 😁

2022-01-31 07:40 UTC, emteknetnz approved these changes

2022-01-31 07:41 UTC, merged

2022-04-25 22:11 UTC, emteknetnz commented
This PR ended up indirectly causing a lot of regressions - I've created a PR to revert it https://github.com/silverstripe/silverstripe-framework/pull/10291