Fixes various typos with codespell
silverstripe/silverstripe-framework pull request #10177
Opened 2021-12-12 19:51 UTC by lerni

Mostly fixes typos in strings, docs & comment

Also some variablenames are renamed:
- `famework/src/Core/CoreKernel.php` `$environment`
- `vendor/silverstripe/framework/src/ORM/DataObject.php` `$identifier`
- `vendor/silverstripe/framework/tests/php/Forms/GridField/GridFieldSortableHeaderTest.php` `$component`

Had a play with [codspell](https://github.com/codespell-project/codespell) - this PR is the outcome. Hopefully someone is willing to review - it's a lot.

2021-12-12 21:48 UTC, michalkleiner commented
Thanks @lerni, nice job. Been thinking of going through the codebase of the core modules at some point, too.

I've started reviewing the changes, got to 30 files so far, the majority is looking good. Should get through the rest today.

2021-12-12 22:48 UTC, michalkleiner commented on src/Core/Injector/Injector.php
> +     * Specify ya service type prototype
```suggestion
     * Specify a service type prototype
```

2021-12-13 00:02 UTC, michalkleiner commented on tests/php/Forms/GridField/GridFieldSortableHeaderTest.php
>          $htmlFragment = $compontent->getHTMLFragments($gridField);
```suggestion
        $htmlFragment = $component->getHTMLFragments($gridField);
```

2021-12-13 00:03 UTC, michalkleiner commented on tests/php/Forms/GridField/GridFieldSortableHeaderTest.php
>          $listA = $compontent->getManipulatedData($gridField, $list);
```suggestion
        $listA = $component->getManipulatedData($gridField, $list);
```

2021-12-13 00:08 UTC, michalkleiner requested changes
Ok, went over all the changes.

@lerni the change in `GridFieldSortableHeaderTest` needs further work, the PR only renames the initial variable when created, but not when used. I've added two change suggestions, but you'd need to go through the class and update all the occurrences.

2021-12-13 00:08 UTC, michalkleiner commented
Three minor things to confirm with @maxime-rainville or @emteknetnz:
1. The change to `CoreKernel` about renaming the protected `$enviroment` variable. Within the framework, I'd say this change is fine, but people might have their own kernels extending CoreKernel and not using the getter/setter methods. Though targetting main I'd be happy to mention this in the docs and keep the fix.
2. Fixing typos in changelogs where they were basically generated from commit messages including the same typos, so it would become disconnected, though the commit hash still stays valid. For better legibility of past changelogs, I'd be for keeping the spelling fixes, I don't expect people searching the history of the repo for exact commit message matches.
3. Inner-method variable name change in `DataObject` is fine with me, but a confirmation would be good.

2021-12-13 00:22 UTC, emteknetnz commented
Yup agree with what @michalkleiner has said re 1. and 2.  3. is fine with the rename

2021-12-13 08:03 UTC, michalkleiner approved these changes
Thanks @lerni, appreciate the contribution.

2021-12-13 08:05 UTC, merged

2021-12-13 08:27 UTC, lerni commented
@michalkleiner thank you for reviewing it so fast: I'm impressed! :100: :heart: May this motivates me checking others like CMS with codespell as well :wink: