FIX Look for existing modules in vendor folder rather than base folder
silverstripe/silverstripe-framework pull request #10179
Opened 2021-12-13 04:28 UTC by emteknetnz

Issue https://github.com/silverstripeltd/product-issues/issues/507

2021-12-13 23:03 UTC, maxime-rainville requested changes
Maybe, I'm misunderstanding what this is meant to do. Here's what I did.

1. Manually add fake translation string to `vendor/silverstripe/cms/lang/en.yml`
2. Run `sake dev/tasks/i18nTextCollectorTask

Expected results: Fake translation string is retained when running this PR.
Actual results: Fake translation is removed.

https://www.youtube.com/watch?v=2cmh2Ylp5Jw

2021-12-13 23:06 UTC, emteknetnz commented
did en.yml still have the modification when you checked out the fork? didn't run git status so I don't know if it's still there or not.

2021-12-14 01:50 UTC, maxime-rainville commented
I manually added a fake translation to CMS's `en.yml` file. I didn't commit my fake translation however ... should that make a difference?

2021-12-14 04:25 UTC, emteknetnz commented
It should make no different if it's not committed, it'll simply look in `lang/en.yml`

try `vendor/bin/sake dev/tasks/i18nTextCollectorTask merge=1`

2021-12-15 21:31 UTC, maxime-rainville approved these changes
> try `vendor/bin/sake dev/tasks/i18nTextCollectorTask merge=1`

Missed that one :man_facepalming: 

Looks good. I tested it locally by adding a fake translation to the `en.yml` file and adding a new translation to an existing file. My fake translation didn't get removed and my new translation got picked up.

2021-12-15 21:31 UTC, merged