Allow methods to be used for flexible searchable_fields
silverstripe/silverstripe-framework pull request #10199
Opened 2022-01-13 18:39 UTC by tiller1010

### Summary
Allow methods to be used for flexible `$searchable_fields`. A method name can be added as a `$searchable_fields` key. The method should return an array of fields that can be used when using this search field in a GridFieldFilterHeader.

### Testing
- [ ] create a DataObject with `$searchable_fields`
- [ ] set a key to a method name that returns the appropriate search fields in an array (see comments in SearchContext)
- [ ] create records that use the searchable fields returned in your method
- [ ] confirm the search results will show any records that match at least one of the returned search fields

### Concerns
- It was necessary for me to define the `field` type in the searchable field options.

2022-02-01 22:23 UTC, emteknetnz commented
Could you help me understand what this is supposed to do from a UI perspective?  Based on
```
                        public function getSearchableFirstName($queryName = '')
                        {
                            return [
                                'Customer.FirstName' => $queryName,
                                'ShippingAddress.FirstName' => $queryName,
                            ];
                        }
```
I'm assuming that when a user searches on FirstName it would now search on both the Customer.FirstName database field as well as the ShippingAddress.FirstName field?

2022-02-02 21:56 UTC, tiller1010 commented
@emteknetnz 
>I'm assuming that when a user searches on FirstName it would now search on both the Customer.FirstName database field as well as the ShippingAddress.FirstName field?

That's exactly right.

2022-02-04 05:07 UTC, emteknetnz requested changes
I'm finding the syntax of this confusing.  I don't think there's a need for a separate method as we're limited to what's in the database, and we cannot use dynamic content in this context i.e. filtering a DataList (as far as I'm aware, maybe I'm wrong)

I think putting everything in $searchable_fields would make more sense

```
private static $searchable_fields = [
    'CustomFirstName' => [
        'title' => 'First Name',
        'field' => TextField::class,
        'filter' => 'PartialMatchFilter',
        'match_any' => [
            'Customer.FirstName,
            'ShippingAddress.FirstName'
        ]
    ]
]
```

To merge this PR we'll also need unit test coverage added to this PR, as well as documentation about this additional functionality updated [here](https://github.com/silverstripe/silverstripe-framework/blob/4/docs/en/02_Developer_Guides/00_Model/11_Scaffolding.md) rather than as an code comment as it is now

2022-02-04 23:43 UTC, GuySartorelli commented on docs/en/02_Developer_Guides/00_Model/11_Scaffolding.md
> +Use a single search field that matchs on multiple database fields with `'match_any'`
```suggestion
Use a single search field that matches on multiple database fields with `'match_any'`
```

2022-02-08 00:47 UTC, michalkleiner commented on tests/php/ORM/Search/SearchContextTest/Address.php
> +}
Please keep an empty line at the end of the files, thanks

2022-02-08 00:47 UTC, michalkleiner commented on tests/php/ORM/Search/SearchContextTest/Customer.php
> +}
Please keep a new line at the end of the files, thanks

2022-02-08 00:47 UTC, michalkleiner commented on tests/php/ORM/Search/SearchContextTest/Order.php
> +}
Please keep a new line at the end of the files, thanks

2022-02-08 20:52 UTC, michalkleiner approved these changes
Looks ok from my perspective, thanks!

2022-02-09 02:51 UTC, emteknetnz requested changes
Great work.

I've tested this locally to confirm it works as expected

Some very minor changes then I'm happy to merge

There's some PHPCS linting to fix as well https://app.travis-ci.com/github/silverstripe/silverstripe-framework/jobs/558865008

2022-02-09 02:51 UTC, emteknetnz commented on src/ORM/Search/SearchContext.php
> +                            foreach($searchFields as $dottedRelation){
```suggestion
                            foreach ($searchFields as $dottedRelation){
```

2022-02-09 02:51 UTC, emteknetnz commented on src/ORM/Search/SearchContext.php
> +                                // Apply join
I don't think we need these inline comments explaining the code or the line breaks above them

2022-02-09 02:51 UTC, emteknetnz commented on docs/en/02_Developer_Guides/00_Model/11_Scaffolding.md
> +                // Searching with "First Name" will show Orders with matching Customer or Address names
```suggestion
                // Searching with the "First Name" field will show Orders matching either Customer.FirstName or ShippingAddress.FirstName
```

2022-02-09 20:39 UTC, emteknetnz approved these changes

2022-02-09 20:40 UTC, merged