URLSegmentFilter fix for apostrophe
silverstripe/silverstripe-framework pull request #10191
Opened 2022-01-06 14:51 UTC by oilee80

Strips it out as it gets encoded as `%E2%80%99` in the DB

2022-01-07 10:07 UTC, dhensby commented
shouldn't this be covered by the `'/[^A-Za-z0-9\-]+/u' => '', // remove non-ASCII chars, only allow alphanumeric and dashes
` rule?

2022-01-07 11:50 UTC, lbradley-mm commented
If you have allow multi byte enabled (which is the case in `BlogObject::generateURLSegment()`)
Maybe it needs tweaking in there though

2022-01-07 11:51 UTC, lbradley-mm commented
@dhensby if you have allow multi byte enabled (which is the case in `BlogObject::generateURLSegment()`)
Maybe it needs tweaking in there though

2022-01-07 12:06 UTC, dhensby commented
Ah, you're right, there's even the next rule removing punctuation which mentions that `'/[\/\?=#:]+/u' => '-', // remove forward slashes, question marks, equal signs, hashes and colons in case multibyte is allowed (and non-ASCII chars aren't removed)`

Well, I suppose it depends on what the purpose of this is. Do we only want to allow Latin alphabet and numbers plus dashes to represent spaces (this is pretty old school) or do we want to allow multibyte chars (ie: non-latin chars) in our URLs?

That then brings us on to whether we actually want to remove punctuation now that URLs support multi-byte in general, including apostrophes. To me, it doesn't really make sense to allow emojis and non-latin chars in URLs but not apostrophes. The fact that they are encoded to `%E2%80%99` is absolutely intended and means in modern browsers your URL will be displayed with the correct char.

For us to start removing these arbitrarily feels a bit regressive and out-of-touch. So, basically, this seems like intended behaviour unless someone can give me a good reason why an apostrophe in a URL is a bad idea?

2022-01-07 12:58 UTC, lbradley-mm commented
In that case we need to look at when the look up is being done in the database so that the multibyte characters are matched
The scenario I had was the character being there meant the Blog Category wasn't found

2022-01-07 13:52 UTC, dhensby commented
ah yes, that's something that's happened before, I think - it's the reversing into the DB

2022-01-16 22:02 UTC, emteknetnz requested changes
So based on the discussion above, we don't want this particular change merged in? Do we still wish to keep this PR open?

2022-01-21 14:52 UTC, dhensby commented
It sounds like there's a problem with producing and then parsing URLs consistently for blog categories, which needs to be looked into to ensure that URLs with unicode chars are correctly matched

2023-12-20 00:05 UTC, GuySartorelli commented
Sounds like an issue needs to be raised that describes the problem - and a new pull request can be made that addresses that problem head-on. Closing this PR as it doesn't seem like it's fixing the problem being discussed.

2023-12-20 00:05 UTC, closed without merging