DOCS: custom graphql filter fields
silverstripe/silverstripe-framework pull request #10192
Opened 2022-01-06 23:04 UTC by unclecheese

Related: https://github.com/silverstripe/silverstripe-graphql/pull/431

2022-01-20 01:49 UTC, emteknetnz requested changes

2022-01-20 01:49 UTC, emteknetnz commented on docs/en/02_Developer_Guides/19_GraphQL/02_working_with_dataobjects/02_query_plugins.md
> +    public static function resolveHasReviewsFilter($list, $args, $context)
Should put in param types in e.g. `array $context`

2022-01-20 01:49 UTC, emteknetnz commented on docs/en/02_Developer_Guides/19_GraphQL/02_working_with_dataobjects/02_query_plugins.md
> +        if (!in_array($comparator, ['eq','ne'])) {
```suggestion
        if (!in_array($comparator, ['eq', 'ne'])) {
```

2022-07-07 01:03 UTC, GuySartorelli commented
Note: This should not be merged here. I have started [the process of migrating docs](https://github.com/silverstripe/silverstripe-framework/issues/10215) to [a new repository](https://github.com/silverstripe/doc) so this PR should be closed and a new one should be created there.

2022-08-05 04:18 UTC, GuySartorelli commented
Closed - docs PR opened at https://github.com/silverstripe/developer-docs/pull/59

2022-08-05 04:18 UTC, closed without merging