PATCH: hide passwords in error logs
silverstripe/silverstripe-framework pull request #10260
Opened 2022-03-15 01:39 UTC by sunnysideup

2022-03-15 10:53 UTC, dhensby requested changes
the pedant in me would like this to be in alphabetical order like all the others, please.

2022-03-17 22:22 UTC, maxime-rainville commented
I've created a parent issue to track some wider work related to this. https://github.com/silverstripe/silverstripe-framework/issues/10261

2022-03-17 22:47 UTC, dhensby approved these changes

2022-03-17 22:50 UTC, maxime-rainville approved these changes
MOG

2022-03-17 23:27 UTC, merged