FIX Correctly remove relations with ManyManyThroughList::removeall
silverstripe/silverstripe-framework pull request #10295
Opened 2022-04-29 02:04 UTC by GuySartorelli

Instead of just setting one side of the relation to null in the through list, remove the rows entirely.
Remove only the relations which match the filters that have already been set on the list.
This is consistent with the way `ManyManyList` works - in fact much of the code for both the functionality and the test are taken straight from that class.

Also some small tidy-up (removing an unnecessary line break and an unused "use" statement)

## Parent Issue
- fixes #10104

2022-04-29 08:15 UTC, kinglozzer commented
Given that the join records are DataObjects in their own right, do you think we’d be better approaching this in a similar way to `ManyManyThroughList::removeByID()`? It’s a little slower, but deletions are rarer than writes and it does allow for `onBeforeDelete`/`onAfterDelete` etc on the join records to be invoked

2022-04-29 09:51 UTC, GuySartorelli commented
Hmm I'm conflicted between wanting to keep it performant and wanting to let people use those extension points...

Would it be reasonable to make it configurable? We could add a new configuration boolean on the join record class (something like `private static bool $use_orm_for_removeall` - obviously we can't declare this but we can document it, and the default null is falsey so that goes with how I'd want this to work).

Then in removeall if that config is falsey we use this or a similar approach, and if it's true we use the ORM so that any project that explicitly needs those hooks called on a join record can have that functionality available.

Keeps it snappy for the majority but gives flexibility to the minority that need it.

2022-04-29 10:55 UTC, kinglozzer commented
Maintaining two codepaths based on a config flag isn’t ideal 😕

I think we should be consistent with how we handle the “through” records too. When `$manyManyThrough->add($item)` is called, you can use `onBeforeWrite`/`onAfterWrite` hooks, ownership hooks etc, so I think we should offer the same functionality on deletions. I think that was part of the appeal of building the “through” API.

Performance-wise there shouldn’t really be any noticeable difference until you reach hundreds/thousands of join records. That sort of thing tends to be handled by scheduled tasks rather than synchronous user actions.

2022-04-29 11:04 UTC, kinglozzer commented
Just rethinking this, we’re changing behaviour from un-assigning a join record to deleting a join record. For old `many-many` that’s fine, but given that the join records are full DataObjects in `many-many-through` is that definitely desirable? I can’t think of a use case off the top of my head where you’d want to keep the unassigned join records, but I suppose there could be one...

Would we be safer to change this PR to _just_ fix the filter issue and leave the “unassign” behaviour in place?

2022-05-02 03:43 UTC, emteknetnz requested changes
It looks good, though could you bump up the number of fixtures used here from 2 to 3.  Reason being is so that we can filter out 2 and assert there are 3 remaining, this is just to ensure it's removing 'all' rather than 'first'

Also, if there's not a test already, could you also add a test for ->removeAll() on an unfiltered list just to ensure that it removes everything

2022-05-02 05:07 UTC, GuySartorelli commented
@emteknetnz do you have any opinions on using `SQLDelete` vs for example looping through and calling `remove()` to allow the ORM hooks on the join objects to be called?

2022-05-03 01:01 UTC, GuySartorelli commented
Discussed with @emteknetnz offline - he says it makes sense to use the ORM for this situation, so that's two in favour of the ORM. I'll take that approach.

2022-05-04 22:01 UTC, GuySartorelli commented
> could you also add a test for ->removeAll() on an unfiltered list just to ensure that it removes everything

That's part of this same `testRemoveAll()` method - for clarity I'll split out out so there's one method for testing unfiltered `revoveAll()` and one for filtered.

2022-05-04 23:24 UTC, GuySartorelli commented
**NOTE** I have also changed the IDs passed into the remove callbacks - the `removeCallbacks()` method defined in `RelationList` implies that these should be the IDs of the _related_ items being removed, not the join records. When I added the child0 fixture and ran the unit tests, I got the following errors which clearly indicate that the tests were expecting IDs of the _related records_ and not the join records.

> There were 3 failures:
> 
> 1) SilverStripe\ORM\Tests\ManyManyThroughListTest::testCallbackOnSetById
> Failed asserting that two arrays are equal.
> --- Expected
> +++ Actual
> @@ @@
>  Array (
> -    0 => 3
> +    0 => 2
>  )
> 
> /var/www/vendor/silverstripe/framework/tests/php/ORM/ManyManyThroughListTest.php:450
> /var/www/vendor/sminnee/phpunit/phpunit:52
> /var/www/vendor/bin/phpunit:117
> 
> 2) SilverStripe\ORM\Tests\ManyManyThroughListTest::testRemoveCallbackOnRemove
> Failed asserting that two arrays are equal.
> --- Expected
> +++ Actual
> @@ @@
>  Array (
> -    0 => 3
> +    0 => 2
>  )
> 
> /var/www/vendor/silverstripe/framework/tests/php/ORM/ManyManyThroughListTest.php:483
> /var/www/vendor/sminnee/phpunit/phpunit:52
> /var/www/vendor/bin/phpunit:117
> 
> 3) SilverStripe\ORM\Tests\ManyManyThroughListTest::testRemoveCallbackOnRemoveById
> Failed asserting that two arrays are equal.
> --- Expected
> +++ Actual
> @@ @@
>  Array (
> -    0 => 3
> +    0 => 2
>  )
> 
> /var/www/vendor/silverstripe/framework/tests/php/ORM/ManyManyThroughListTest.php:499
> /var/www/vendor/sminnee/phpunit/phpunit:52
> /var/www/vendor/bin/phpunit:117

2022-05-09 02:55 UTC, sabina-talipova approved these changes

2022-05-09 03:00 UTC, sabina-talipova commented
I have approved, but there is some Travis test failed. Could you check it please.
```
1) SilverStripe\Core\Tests\MemoryLimitTest::testIncreaseMemoryLimitTo
Failed to set memory limit to 67108864 bytes (Current memory usage is 182976512 bytes) 
```

2022-05-12 02:55 UTC, GuySartorelli commented
FYI the failure is on the `nightly` php build which is no longer used in our travis config from 4.10 onwards. I think it's safe to ignore that.

2022-05-15 23:05 UTC, maxime-rainville reviewed
Looks good at first glance.

Can you just confirm what happens in the following scenarios:
- the same relations is defined multiple times. e.g.: Example Class A has a many-many relation to Class B. One object A is related multiple times to the same Object B.
- What happens if the ManyManyThrouh object is versioned? Do we want to add a unit test specifically for that?

Just want to make sure we've covered all our basis.

2022-05-15 23:52 UTC, GuySartorelli commented on src/ORM/ManyManyThroughList.php
> +        if ($this->removeCallbacks && $itemID) {
> Does our `ManyManyThrough` implementation allow us to add the same record multiple times?

Not directly - if you call `add()` on a `ManyManyThroughList` and pass in an object that is already part of that relation, it won't add it a second time. You _can_ however manually create a new join object which duplicates an existing join object, which would effectively result in having added the item twice. This seems to act identically to if it was only added the once, however.

> what's the expected behavior if you remove by ID and there's more than one record for that ID?

Unless you're doing weird stuff, you can only add one join record per relation - you can cheat this as mentioned above, but in that case `removeByID()` will (and should) remove _all_ of the join records for that relation.

2022-05-16 00:05 UTC, GuySartorelli commented
> What happens if the ManyManyThrouh object is versioned? Do we want to add a unit test specifically for that?

I don't know what if any thought was put into this scenario when `ManyManyThroughList` was implemented - it seems that versioning the join class doesn't affect anything at all. The `staged' aka draft version is always used, so publishing and unpublishing updates the version and live tables, but doesn't actually affect the functionality of the list. You always only see the draft relations.

`removeAll()` and `removeByID()` also ignore the live and version tables - they only operate on the draft. So you can have a published relation object where there's no draft object - but again, that doesn't affect anything. The list just won't see the relation at all.

Given the above, I think versioning is out of scope for this PR. At most, I could add a note in the docs that versioning the join objects isn't currently supported.

2022-05-16 00:40 UTC, maxime-rainville approved these changes
My pesky question have been addressed.

2022-05-17 02:08 UTC, merged