NEW: Mock sleep unit test utility.
silverstripe/silverstripe-framework pull request #10317
Opened 2022-05-13 01:21 UTC by mfendeksilverstripe

# NEW: Mock sleep unit test utility.

Simple utility function for unit tests. Use instead of `sleep()`. I found this quite handy is several projects, we might as well make the code reusable.

2022-05-13 04:34 UTC, GuySartorelli commented
I don't think we should be including methods that are only meant to be called in tests into production codebases.
There is some of that already, but it's too late to decouple those instances in the current major. I don't think we should be adding more.

I'll leave this open for a day or two in case a core committer disagrees with me, though.

2022-05-13 04:38 UTC, mfendeksilverstripe commented
@GuySartorelli Fair enough, is there a better place for it though? For example we could add a TestOnly service maybe under the Dev namespace?

2022-05-13 04:42 UTC, GuySartorelli commented
I'm not sure, to be honest. I'd love (in the long term) for all of the test-related stuff to be moved out of framework altogether, and be in its own module that can be included as a dev dependency... but we're a ways off doing something like that just yet.

This might be the best place for it at the moment, to be honest, now that I've spent a bit more time considering it.
I still won't merge immediately in case there are opinions from other core committers on this but yeah probably this is the spot for this method, if there is a spot for it, in the current state of things.

2022-05-13 04:44 UTC, mfendeksilverstripe commented
All good @GuySartorelli , happy to keep the PR open. Having a separate module for this sounds great.

2022-05-15 06:42 UTC, michalkleiner approved these changes
Fair consideration from Guy, I would agree here. We can wait forever or just get it in now and move it out later with other stuff.

2022-05-15 10:44 UTC, michalkleiner commented
Let's wait a day or two if Max or Steve have a different view, and if not we can get it in.

2022-05-17 23:15 UTC, emteknetnz requested changes
This does seem like the wrong place

Somewhere in src/Dev seems like it would be better.  There are already some other Test*.php classes there such as TestSession and TestMailer

So perhaps create a new class Dev/TestDateTime.php and put this method it there?

2022-05-18 08:46 UTC, dhensby commented
Couldn't it be added to `SapphireTest` or some part of the PHPUnit framework to allow tests to call `$this->addTime()` or similar?

How would one expect this to work if `mock_now` was not set?

2022-05-19 05:00 UTC, emteknetnz commented
I'd be inclined to just delete the PHPUnit 5.7 version, it's an ancient API we shouldn't be developing for it

What happens if you put a `sleep(3)` in your unit test?

2022-05-19 05:14 UTC, GuySartorelli commented
> I'd be inclined to just delete the PHPUnit 5.7 version,

Just for the sake of clarity: I assume you mean the 5.7 version _of the new method_, not of the class itself.

2022-05-19 06:31 UTC, dhensby commented
Cool. Is the time reset after each test? I assume it is, just making sure...

2022-05-19 06:34 UTC, GuySartorelli commented
If it isn't, that's a fundamental issue with the mock now functionality as a whole, not a new problem introduced with this PR.

2022-05-19 08:10 UTC, dhensby commented
Right, but a dev who implements `mock_now` is then responsible for the tear down of that test. This feature hides it behind syntactic sugar, so it'd be understandable that a dev that uses it assumes the date is reset at the end of the test for them.

2022-05-19 08:14 UTC, dhensby commented
Looks like it is handled: https://github.com/silverstripe/silverstripe-framework/blob/4/src/Dev/SapphireTest.php#L630-L632

2022-05-27 01:44 UTC, GuySartorelli commented
@emteknetnz You've still got a review here with requested changes - is that for removing the new method on the old phpunit class? I don't think it's worth holding up merging for that personally, are you okay with the PR as is or do you still want some changes made?

2022-05-27 01:50 UTC, emteknetnz commented
I'm not too attached, feel free to merge if you see fit

2022-05-27 01:51 UTC, GuySartorelli approved these changes

2022-05-27 01:52 UTC, merged