use callable as well as creator
silverstripe/silverstripe-framework pull request #10321
Opened 2022-05-16 04:40 UTC by PawelSuwinski

This makes core object creator a more universal factory and its a natural consequence of:

https://github.com/silverstripe/silverstripe-framework/blob/cb37869bac40ffae2458654f842bcb173be61931/src/Core/Injector/Injector.php#L430-L432

Example of extended syntax usage:

```
# app/_config/services.yml
  GuzzleHttp\HandlerStack:
    class: GuzzleHttp\HandlerStack::create
```

2022-05-16 10:24 UTC, dhensby commented
Looks like a reasonable addition that could be pretty powerful.

I think we'd need to see some decent tests here to cover off the use-cases and that injector does indeed create instances as expected this way as well as additions to the documentation.

2022-05-18 00:56 UTC, emteknetnz requested changes
Does seems like a good addition

As Dan mentioned, we need tests + docs

The example given in the original description refers to https://github.com/guzzle/guzzle/blob/master/src/HandlerStack.php#L47

2022-05-18 00:56 UTC, emteknetnz commented on src/Core/Injector/InjectionCreator.php
>      public function create($class, array $params = [])
```suggestion
    public function create($classOrMethod, array $params = [])
```

Also update references to `$class` elsewhere in this method

2022-05-18 07:07 UTC, PawelSuwinski commented
> As Dan mentioned, we need tests + docs

OK, I will add some.

2022-06-02 04:54 UTC, emteknetnz commented
I'm in two minds about this one.

Apologies in advance for any incorrect assumptions I've made here, this is a fairly complex topic

I sort of like this idea here, though I am quite worried this will lead to making the yml config even more confusing than it is

The comment about `$class` not needing to be a class, instead allowing a compound statement, went in 10 years ago when Injector.php was first created.  It's not a new thing - https://github.com/silverstripe/silverstripe-framework/commit/b269badfbe8daa77c4d80d9de1106160d6206d91#diff-fe633772e4ca1ed70c69ad396df29e7447d318434f63deb1b97c13168ef874dbR320

It's kind of messy having `create($class,` because `create($classOrMethod,` and then having `constructor` act as `methodParameters`.  The YML config for service classes is already confusing enough as it is, this will only make it more confusing.

It seems like this would be far cleaner that if instead of essentially high-jacking the keys 'class' and 'constructor', there were additional keys available 'method' and 'arguments' (likely we'd use different key names if we were to do this)

I think this work better if we didn't do this in InjectionCreator as it implements the Factory interface, which we cannot update without breaking API, so would need to happen in CMS5.  However it might work if this was instead done directly in `Injector::instantiate()` instead? e.g.

```php
if (isset($spec['method'])) {
    $method = $spec['method'];
    if (!is_callable($method)) {
        throw new InjectorNotFoundException("Method '{$method}' is not callable");
    }
    $arguments = $spec['arguments'] ?? [];
    $object = call_user_func_array($method, $arguments);
    if (!is_object($object)) {
        throw new InjectorNotFoundException("Method '{$method}' does not return an object");
    }
} else {
    $factory = isset($spec['factory']) ? $this->get($spec['factory']) : $this->getObjectCreator();
    $object = $factory->create($class, $constructorParams);
}   
```

At the same time though, I'm also not keen on this change because it's changing what `%$` can represent.  In the yml example provided in this pull request:

```yml
SilverStripe\Core\Injector\Injector:
  LogMiddleware:
    class: 'GuzzleHttp\Middleware::log'
    constructor: ['%$Psr\Log\LoggerInterface', '%$GuzzleHttp\MessageFormatter', 'info']
  GuzzleHttp\HandlerStack:
    class: 'GuzzleHttp\HandlerStack::create'
    calls:
      - [push, ['%$LogMiddleware']]
  GuzzleHttp\Client:
    constructor:
      -
        handler: '%$GuzzleHttp\HandlerStack'
```

[GuzzleHttp\Middleware::log](https://github.com/guzzle/guzzle/blob/master/src/Middleware.php#L192) returns a callable, not a class

Therefore `'%$LogMiddleware'` is now not the usual service class / singleton, instead here it's a callable.  This would not have been possible out-of-the-box before because InjectorCreator goes `new $class(...$params);`, so now we're changing what `%$` can mean, which I'm not particularly keen to do.

I'm not really sure where to go with this one.  @dhensby @maxime-rainville @GuySartorelli do you have any views on this one?

2022-06-02 04:55 UTC, emteknetnz requested changes
Need to decide if this is something we want to proceed with at this stage

2022-06-02 05:01 UTC, GuySartorelli commented
This seems like a really useful and flexible feature on the surface, but it does feel a bit _too_ flexible. I would expect the result of `Injector::inst()->get('some-service')` to always be some object, but with this change it feels like the result could be effectively anything.

2022-06-02 05:56 UTC, PawelSuwinski commented
> I would expect the result of `Injector::inst()->get('some-service')` to always be some object, but with this change it feels like the result could be effectively anything.

Nope, object always:
https://github.com/PawelSuwinski/silverstripe-framework/blob/InjectionCreator_callableExtension/src/Core/Injector/InjectionCreator.php#L14

2022-06-02 06:20 UTC, PawelSuwinski commented
> It's kind of messy having `create($class,` because `create($classOrMethod,` and then having `constructor` act as `methodParameters`. The YML config for service classes is already confusing enough as it is, this will only make it more confusing.

Yes, a bit, I think that better place for it in factory setting I didn't want to bring new things and concepts just wanted to use what I found here. IMHO a `factory`  that can point only to Factory interface is unnecessary too restrictive. Any callable method will good as well, and `constructor` wouldn't be confusing then, as said in Factories docs it is arguments for factory method. I can change this PR this way. 

> Therefore `'%$LogMiddleware'` is now not the usual service class / singleton, instead here it's a callable.

Not exactly, this kind of callable it is still an object - Closure instance, so everything is still right.

2022-06-02 21:02 UTC, emteknetnz commented
OK, if we're validating that things are Objects I'm less concerned because it means that the meaning of `%$` is unchanged.

There isn't currently any type checking within Injector.php that `$spec['factory']` implements `Factory`, so it seems like what we might want then is the key 'factory_method' added?  Then perhaps we could do something like this:

*Injector.php*
```php
$factory = isset($spec['factory']) ? $this->get($spec['factory']) : $this->getObjectCreator();
if (($factory instanceof Factory) || !isset($spec['factory_method']) || !method_exists($spec['factory'], $spec['factory_method'])) {
    // retain existing functionality
    $object = $factory->create($class, $constructorParams);
} else {
    // new functionality
    $method = $spec['factory_method'];
    $object = $factory->$method($class, $constructorParams);
    if (!is_object($object)) {
        $class = get_class($factory);
        throw new InjectorNotFoundException("Method '{$method}' on '{$class}' does not return an object");
    }
}
```

How does this sound?

2022-06-03 08:45 UTC, PawelSuwinski commented
> How does this sound?

Quite well. I added support for static factory method, not every factory class  allows instantiation.

So here it is.

2022-06-07 00:10 UTC, emteknetnz requested changes
It's looking good, a few more changes to make

2022-06-07 16:37 UTC, PawelSuwinski commented
Done.

2022-06-08 09:48 UTC, maxime-rainville commented
Just double checking my understanding of the use case here. 

The idea is that occasionally you will use a library that expect you to call a "factory method" on class to create an instance rather than a regular constructor. If you want to instantiate that class with Injector, your only option right now is to create a proper Factory class.

The point of this PR is to update the Injector so that we can simply tell Injector to use the factory method and avoid creating a full factory class.

If my understanding, this seems like a useful approach and something I would support.

2022-06-08 10:29 UTC, PawelSuwinski commented
> The point of this PR is to update the Injector so that we can simply tell Injector to use the factory method and avoid creating a full factory class.


That's right. A lot of libs use factory design patterns having it's own ready to use factory methods (like a GuzzleHttp from the example) so factory (class) is already there just method name differs than the one imposed by Factory interface.

2022-06-09 01:30 UTC, emteknetnz commented
Just noting for posterity that symfony simply allows setting the `factory_method` as the second argument when creating a factory via yml

https://symfony.com/doc/current/service_container/factories.html#static-factories

In a later version of framework, it might be good to align our approach with symfony's, remove the php `Factory` interface from Silverstripe where the `create` method is required to be the `factory_method`

It would also be good to rename `constructor` to `arguments`

2022-06-09 01:55 UTC, emteknetnz approved these changes
Great work.

Have tested locally to confirm everything works as expected

2022-06-09 01:57 UTC, merged