FIX PDO in PHP 8
silverstripe/silverstripe-framework pull request #10378
Opened 2022-06-29 02:29 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-framework/issues/10285

One of the methods being fixed here is a backport of https://github.com/silverstripe/silverstripe-framework/pull/10360/files#diff-798255e3f354dbb92e5f7a8702e95634213431cb0553f2e12f633357b7edacdaR562

2022-06-29 22:25 UTC, GuySartorelli requested changes

2022-06-29 22:25 UTC, GuySartorelli commented on src/ORM/Connect/PDOConnector.php
> +            $this->pdoConnection->rollBack();
```suggestion
            return $this->pdoConnection->rollBack();
```
Returns a bool: https://www.php.net/manual/en/pdo.rollback.php

2022-06-29 22:25 UTC, GuySartorelli commented on src/ORM/Connect/PDOConnector.php
> +        }
```suggestion
        }
        // return false because it did not rollback.
        return false;
```

2022-06-30 00:33 UTC, emteknetnz commented on src/ORM/Connect/PDOConnector.php
> +            $this->pdoConnection->rollBack();
Updated

2022-06-30 00:33 UTC, emteknetnz commented on src/ORM/Connect/PDOConnector.php
> +        }
Updated

2022-06-30 01:58 UTC, GuySartorelli approved these changes

2022-06-30 01:58 UTC, merged