Pulls/5/symfony6 translation 2
silverstripe/silverstripe-framework pull request #10491
Opened 2022-09-05 05:53 UTC by emteknetnz

Blocked by https://github.com/silverstripe/silverstripe-framework/pull/10478 - requires that symfony/cache ^6.1 is installed after merging https://github.com/silverstripe/silverstripe-versioned/pull/373

Issue https://github.com/silverstripe/silverstripe-framework/issues/10389

I've rebase this work on top of https://github.com/silverstripe/silverstripe-framework/pull/10478 because symfony-cache ^6.1 is now required by silverstripe/versioned, so that PR is required to get things to work at all - so don't look at this pull-request until that PR is merged

This is not working, broken unit tests locally e.g.

```
i18nTest::testPluralisation
--- Expected
+++ Actual
@@ @@
-'10 months'
+'A month|10 months'
```

`The transchoice tag is deprecated since Symfony 4.2 and will be removed in 5.0. Use the [ICU MessageFormat](https://symfony.com/doc/4.2/translation/message_format.html) with the trans tag instead.`
https://symfony.com/doc/4.2/translation/templates.html

ICU MessageFormat https://symfony.com/doc/current/translation/message_format.html

2022-09-07 04:28 UTC, GuySartorelli commented
@emteknetnz This needs to be rebased after the changes to the upstream PR

2022-09-07 05:38 UTC, emteknetnz commented
Have rebased

2022-09-07 22:35 UTC, GuySartorelli requested changes
This PR has two commits - the first one should be removed, it's a holdover from the old parent PR.

2022-09-07 22:35 UTC, GuySartorelli commented on composer.json
> +        "symfony/translation-contracts": "^3.1",
Why is this new dependency needed?

2022-09-08 00:16 UTC, emteknetnz commented
Updated

2022-09-08 00:29 UTC, GuySartorelli approved these changes

2022-09-08 00:29 UTC, merged