[TASK] Remove outdated IE6 condition in base tag
silverstripe/silverstripe-framework pull request #10523
Opened 2022-10-03 10:54 UTC by ayacoo

Related #10502

2022-10-05 00:22 UTC, GuySartorelli commented
There are some failing tests in the CI - please resolve those.

2022-10-06 19:29 UTC, ayacoo commented
From my point of view, the first two assertions (line 958 - 978) can be removed completely. However, as I am new here, I did not want to simply decide this and therefore adapted the tests simply for the time being.

2022-10-06 20:31 UTC, GuySartorelli commented
One of the tests is still failing.
I agree that it makes sense to remove the tests that were previously testing the functionality which you are removing.

2022-10-09 08:54 UTC, ayacoo commented
On the last run-through, I am puzzled as to why no slash is added there. Does anyone have any ideas about this? Apparently a placeholder %base_tag% in the test is replaced, but looking around the project, I don't have a clever idea where this happens.

2022-10-10 23:40 UTC, GuySartorelli requested changes

2022-10-10 23:40 UTC, GuySartorelli commented on src/View/SSViewer.php
> +        return '<base href="' . Director::absoluteBaseURL() . '" />';
```suggestion
        return '<base href="' . Director::absoluteBaseURL() . '">';
```
Modern browsers don't require this to be self-closing. That's true of any browser that supports HTML4+

2022-10-10 23:40 UTC, GuySartorelli commented on tests/php/View/SSViewerTest.php
> +            '/<head><base href=".*" \/><\/head>/',
```suggestion
            '/<head><base href=".*"><\/head>/',
```

2022-10-10 23:41 UTC, GuySartorelli commented
Not sure why the slash wasn't being added - but it's actually better that it isn't added since this tag doesn't need to be self-closing.

2023-11-12 11:46 UTC, closed without merging