Restrict embed shortcode attributes
silverstripe/silverstripe-framework pull request #10582
Opened 2022-11-20 23:28 UTC by emteknetnz

2022-11-20 23:59 UTC, GuySartorelli requested changes

2022-11-20 23:59 UTC, GuySartorelli commented on tests/php/Forms/GridField/GridFieldSortableHeaderTest.php
> +        $component = $gridField->getConfig()->getComponentByType(GridFieldSortableHeader::class);
```suggestion
```

2022-11-21 00:01 UTC, emteknetnz commented on tests/php/Forms/GridField/GridFieldSortableHeaderTest.php
> +        $component = $gridField->getConfig()->getComponentByType(GridFieldSortableHeader::class);
Updated

2022-11-21 00:06 UTC, GuySartorelli approved these changes
MOG

2022-11-21 00:30 UTC, merged