DEP Use masterminds/html5 for HTMLValue
silverstripe/silverstripe-framework pull request #10647
Opened 2023-01-16 01:35 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-framework/issues/10528

2023-01-16 01:54 UTC, emteknetnz commented on tests/php/View/Parsers/HTMLValueTest.php
> +<?php
This is copied from https://github.com/silverstripe/silverstripe-html5/blob/2/tests/HTML5ValueTest.php

2023-01-16 01:55 UTC, emteknetnz commented on tests/php/View/Parsers/HTMLValueTest.php
> +            '<p>Enclosed Value</p><p>a' => '<p>Enclosed Value</p><p>a</p>',
There is a very minor difference in this test vs https://github.com/silverstripe/silverstripe-html5/blob/2/tests/HTML5ValueTest.php#L22 where we use `<p>a` here vs `</p>` in the other test - reason being that using masterminds/html5 the `</p>` will simply be removed, which is a better behavior IMO

2023-01-16 04:58 UTC, emteknetnz commented on src/View/HTML.php
> +            return "<{$tag}{$preparedAttributes}>";
No self-closing tags for void elements in html5 - https://developer.mozilla.org/en-US/docs/Glossary/Void_element#self-closing_tags

2023-01-17 09:19 UTC, maxime-rainville requested changes
Looks great. Just a few minor tweaks are needed.

Do we want to include test with a DataObject with a pre-existing HTMLText field with some HTML4 content to see what the migration will looked like?

2023-01-17 09:19 UTC, maxime-rainville commented on _config/html.yml
>    # Shorthand
This comment probably needs to be removed as well.

```suggestion
```

2023-01-17 09:19 UTC, maxime-rainville commented on _config/html.yml
> -  HTMLValue: '%$SilverStripe\View\Parsers\HTMLValue'
Do we need to explicitly call this alias as deprecated? Do we even have a way to do that?

For reference, it looks like we are using this alias in:
- https://github.com/silverstripe/silverstripe-externallinks/blob/2/src/Tasks/CheckExternalLinksTask.php#L184
- https://github.com/silverstripe/silverstripe-userforms/blob/5/code/Model/EditableFormField/EditableLiteralField.php#L86

2023-01-17 09:19 UTC, maxime-rainville commented on src/View/Parsers/HTML4Value.php
> -class HTML4Value extends HTMLValue
Confirmed this is being deprecated in https://github.com/silverstripe/silverstripe-framework/pull/10648

2023-01-17 09:19 UTC, maxime-rainville commented on src/View/Parsers/HTMLValue.php
> +            $res = str_replace("</$tag>", '', $res);
I would expect the HTML5 parser to take care of this. When I comment it out locally, all the unit test still pass just fine.

If it is needed, then we should include a test case to cover it. Also, we might have a case sensitivity problem. So we probably should use `str_ireplace` instead.

2023-01-17 09:19 UTC, maxime-rainville commented on tests/php/View/Parsers/HTML4ValueTest.php
> -                => '/bodu&gt;/body&gt;'
These two test case still look relevant and should be copied over to `HTMLValueTest`

2023-01-17 09:19 UTC, maxime-rainville commented on tests/php/View/Parsers/HTML4ValueTest.php
> -            '""\'\'\'"""\'""<<<>/</<htmlbody><a href="test-link"<<>'
This test case is not in `HTMLValueTest`

2023-01-17 09:19 UTC, maxime-rainville commented on tests/php/View/Parsers/HTML4ValueTest.php
> -    public function testAttributeEscaping()
This test case is not in `HTMLValueTest`.

2023-01-17 21:30 UTC, emteknetnz commented on _config/html.yml
> -  HTMLValue: '%$SilverStripe\View\Parsers\HTMLValue'
> Do we need to explicitly call this alias as deprecated? Do we even have a way to do that?

I don't think so? It's not deprecated, it's essentially just some yml config we're removing.  Bit of an edge case, I've created PR to add to changelog - https://github.com/silverstripe/developer-docs/pull/135

2023-01-17 21:35 UTC, emteknetnz commented on _config/html.yml
> -  HTMLValue: '%$SilverStripe\View\Parsers\HTMLValue'
Have created PRs to not use shorthand for injection
- https://github.com/silverstripe/silverstripe-externallinks/pull/88
- https://github.com/silverstripe/silverstripe-userforms/pull/1184

2023-01-17 21:54 UTC, emteknetnz commented on _config/html.yml
>    # Shorthand
Removed

2023-01-17 21:54 UTC, emteknetnz commented on src/View/Parsers/HTMLValue.php
> +            $res = str_replace("</$tag>", '', $res);
Removed

2023-01-17 21:55 UTC, emteknetnz commented on tests/php/View/Parsers/HTML4ValueTest.php
> -                => '/bodu&gt;/body&gt;'
Added

2023-01-17 21:57 UTC, emteknetnz commented on tests/php/View/Parsers/HTML4ValueTest.php
> -            '""\'\'\'"""\'""<<<>/</<htmlbody><a href="test-link"<<>'
Parser cannot parse it, I think it's fine to leave this last one out and not expect the parser to parse because it is wildly invalid HTML

2023-01-17 21:58 UTC, emteknetnz commented on tests/php/View/Parsers/HTML4ValueTest.php
> -    public function testAttributeEscaping()
Added

2023-01-17 22:37 UTC, maxime-rainville approved these changes
LGTM

2023-01-17 22:38 UTC, merged