Add config to allow dotenv override
silverstripe/silverstripe-framework pull request #10660
Opened 2023-01-27 00:40 UTC by OldStarchy

This is a non-breaking workaround/fix for #10518.

Suppose you're running SilverStripe in a docker dev container that provides a default `SS_DATABASE_NAME: site` in the `docker-compose.yml`, but you want to temporarily use a different database. If you try to set it in the `.env` file it won't work, because the `EnvironmentLoader` won't load any variables that already exist.

This PR adds `SS_ALLOW_DOT_ENV_OVERRIDE` which if set allows `.env` values to override environment variables set on the system/process level.

In 5+ I would prefer this option to be inverted and allow `.env` overrides by default.

2023-01-29 23:37 UTC, emteknetnz requested changes
I'm not sure I see a problem with .env having the highest precedence.  To me that seems correct since it allows developers to override server config that they often cannot control with a file that they usually can control.

> but you want to temporarily use a different database.

Wouldn't it be easier to just change the value in .env rather than docker-composer.yml which would necessitate reloading the container?

Or just not define SS_DATABASE_NAME in .env at all and rely on what's in docker-compose.yml?

2023-01-29 23:54 UTC, emteknetnz commented on src/includes/constants.php
> +            if ($loader->loadFile($dotEnvFile, $allowDotenvOverride)) {
Calls this https://github.com/silverstripe/silverstripe-framework/blob/4/src/Core/EnvironmentLoader.php#L21-L37

2023-01-30 23:22 UTC, OldStarchy commented
You make a good point, though I think the risks are quite low its hard to argue convenience over security.

Also, this would only pose a risk if you have the `SS_ALLOW_DOT_ENV_OVERRIDE` flag set at a system level, which you can just restrict to only doing this in development environments; alternatively, we could swap it out for checking if `SS_ENVIRONMENT_TYPE` is `"dev"` rather than adding a new variable.

2023-01-31 00:33 UTC, emteknetnz commented
>  we could swap it out for checking if SS_ENVIRONMENT_TYPE is "dev" rather than adding a new variable

I'm not keen on any system where dev does not behave like prod. There has been instances of this in the past and it causes confusion and people end up spending lots of time not being able to replicate bugs properly

> this would only pose a risk if you have the SS_ALLOW_DOT_ENV_OVERRIDE flag set at a system level

What happens when SS_ALLOW_DOT_ENV_OVERRIDE is undefined on the server? You could just set SS_ALLOW_DOT_ENV_OVERRIDE=1 in your .env file?

I'm not seeing an easy way forward with this one, this just seems like we're trying to add complication to resolve something that has a pretty easy workaround.

2023-01-31 04:36 UTC, OldStarchy commented
> What happens when SS_ALLOW_DOT_ENV_OVERRIDE is undefined on the server?

Nothing would change from the current behaviour.

> You could just set SS_ALLOW_DOT_ENV_OVERRIDE=1 in your .env file?

`SS_ALLOW_DOT_ENV_OVERRIDE` is only referenced once, just before the `.env` file is loaded, so it's not possible to set it within the `.env` file since by the time the `.env` file is loaded its already too late.

Setting `SS_ALLOW_DOT_ENV_OVERRIDE` in the `.env` has no effect whatsoever.

2023-03-14 07:14 UTC, emteknetnz commented
I'm not keen on this solution since it's a bit confusing and leads to inconsistency for how configuration is read as sometimes it's .env file first and other times it's .env file 2nd, and there are existing workarounds available (e.g. just update your docker-compose.yml file and reload the container)

Since it seems that the primary use case here is to quickly switch the database with a docker container, you might something that allows you to switch the configuration with less friction here https://docs.docker.com/compose/environment-variables/envvars-precedence/

Another option maybe to add SS_DATABASE_PREFIX or SS_DATABASE_SUFFIX  to your .env file and name your temporary database appropriately. I'm assuming that both of those aren't in your docker-compose.yml file.  Those environment variables use this logic https://github.com/silverstripe/silverstripe-framework/blob/4.12/src/Core/CoreKernel.php#L175

2023-03-14 07:14 UTC, closed without merging