API Deprecate Diff in favour of CMS5's HtmlDiff
silverstripe/silverstripe-framework pull request #10677
Opened 2023-02-02 01:05 UTC by GuySartorelli

Deprecates the `Diff` class in favour of the new `HtmlDiff` class in https://github.com/silverstripe/silverstripe-framework/pull/10641

## Parent issue
- https://github.com/silverstripe/silverstripe-framework/issues/10640

2023-02-07 22:08 UTC, sabina-talipova requested changes

2023-02-07 22:08 UTC, sabina-talipova commented on src/View/Parsers/Diff.php
> +        Deprecation::notice('4.13', 'Will be removed without equivalent functionality');
Will it be removed completely? Does `HtmlDiff::cleanHtml()` implement this logic?

2023-02-07 22:08 UTC, sabina-talipova commented on src/View/Parsers/Diff.php
> +        Deprecation::notice('4.13', 'Will be replaced with SilverStripe\View\Parsers\HtmlDiff::cleanHtml()');
Is it correct that `HtmlDiff::cleanHtml()` will replace `Diff::compareHTML()`?

2023-02-07 22:08 UTC, sabina-talipova commented on tests/php/View/Parsers/DiffTest.php
> +        $compare = Deprecation::withNoReplacement(function () use ($from, $to) {
Could we add this at the beginning of the method?
```php
        if (Deprecation::isEnabled()) {
            $this->markTestSkipped('Test calls deprecated code');
        }
```

2023-02-07 22:08 UTC, sabina-talipova commented on tests/php/View/Parsers/DiffTest.php
> +        $actual = Deprecation::withNoReplacement(function () use ($from, $to) {
Could we add this at the beginning of the method?
```php
        if (Deprecation::isEnabled()) {
            $this->markTestSkipped('Test calls deprecated code');
        }
```

2023-02-07 22:08 UTC, sabina-talipova commented on tests/php/View/Parsers/DiffTest.php
> +        $actual = Deprecation::withNoReplacement(function () use ($from, $to) {
Here as well...
```php
        if (Deprecation::isEnabled()) {
            $this->markTestSkipped('Test calls deprecated code');
        }
```

2023-02-07 22:09 UTC, GuySartorelli commented on src/View/Parsers/Diff.php
> +        Deprecation::notice('4.13', 'Will be removed without equivalent functionality');
Fair point, the message for this one should be different. Will update.

2023-02-07 22:11 UTC, GuySartorelli commented on src/View/Parsers/Diff.php
> +        Deprecation::notice('4.13', 'Will be replaced with SilverStripe\View\Parsers\HtmlDiff::cleanHtml()');
Oops, that should say `compareHtml()`, will fix this one.

2023-02-07 22:11 UTC, GuySartorelli commented on tests/php/View/Parsers/DiffTest.php
> +        $compare = Deprecation::withNoReplacement(function () use ($from, $to) {
Yes, good idea.

2023-02-07 22:15 UTC, GuySartorelli commented on tests/php/View/Parsers/DiffTest.php
> +        $compare = Deprecation::withNoReplacement(function () use ($from, $to) {
done

2023-02-07 22:15 UTC, GuySartorelli commented on tests/php/View/Parsers/DiffTest.php
> +        $actual = Deprecation::withNoReplacement(function () use ($from, $to) {
done

2023-02-07 22:15 UTC, GuySartorelli commented on tests/php/View/Parsers/DiffTest.php
> +        $actual = Deprecation::withNoReplacement(function () use ($from, $to) {
done

2023-02-07 22:15 UTC, GuySartorelli commented on src/View/Parsers/Diff.php
> +        Deprecation::notice('4.13', 'Will be replaced with SilverStripe\View\Parsers\HtmlDiff::cleanHtml()');
done

2023-02-07 22:16 UTC, GuySartorelli commented on src/View/Parsers/Diff.php
> +        Deprecation::notice('4.13', 'Will be removed without equivalent functionality');
I have updated the version number to `4.13.0` because after checking it seems that's the correct way to do it.

2023-02-08 01:12 UTC, sabina-talipova approved these changes

2023-02-08 03:36 UTC, merged