API Run some GridField manipulations after canview
silverstripe/silverstripe-framework pull request #10690
Opened 2023-02-14 01:42 UTC by GuySartorelli

Allows optionally having a less performant but more correct pagination by running canView checks before paginating.
I think this is as close as we're going to get to a fix for this without a massive rethink about how we handle permissions.

I opted to have this disabled by default to avoid causing problems for projects with large datasets - but having the option here means anyone who finds this is a problem for them can make a judgment call as to whether the correct pagination is worth the performance hit (and they can make that call on a per-gridfield basis if they really want).

Note that the new `GridField::getListForDisplay()` method has been added to give people a clear API for getting the manipulated list that is ready to be displayed. This is in contrast to `getManipulatedList()` which hasn't been checked for view permissions _and_ may not have had some of its data manipulated yet.
I've replaced calls to `getManipulatedList()` with calls to the new `getListForDisplay()` wherever we actually need the final list which will be displayed (or used for other end-use purposes such as exporting to csv).

## Parent issue
- https://github.com/silverstripe/silverstripe-framework/issues/5995

2023-02-14 01:42 UTC, GuySartorelli commented on src/Forms/GridField/GridField.php
> -
No longer needed as it's already checked in `getListForDisplay()`

2023-02-14 01:42 UTC, GuySartorelli commented on src/Forms/GridField/GridFieldExportButton.php
> -            if (!$item->hasMethod('canView') || $item->canView()) {
No longer needed as it's already checked in `getListForDisplay()`

2023-02-16 23:52 UTC, emteknetnz requested changes
*update: my code example below is very sub-optimal as it runs canView() checks on every record, rather than a potentially filtered subset from getManipulatedList(), basically ignore the example*

I found this PR to be very confusing and added lots of new inconsistently named API that probably doesn't need to be here.

It seems like the whole thing could be done much simpler by just move the canView() checks to GridField::getManipulatedList(), e.g. 

```php
public function getManipulatedList()
{
    $list = $this->getList();

    $checkCanViewBeforeManipulate = GridFieldPaginator::getCheckCanViewBeforeManipulate();

    if ($checkCanViewBeforeManipulate) {
        $list = $this->filterByCanView($list);
    }

    foreach ($this->getComponents() as $item) {
        if ($item instanceof GridField_DataManipulator) {
            $list = $item->getManipulatedData($this, $list);
        }
    }

    if (!$checkCanViewBeforeManipulate) {
        $list = $this->filterByCanView($list);
    }

    return $list;
}

private function filterByCanView(SS_List $list)
{
    $newList = ArrayList::create();
    foreach ($list as $item) {
        if (!$item->hasMethod('canView') || $item->canView()) {
            $newList->add($item);
        }
    }
    return $newList;
}
```

2023-02-17 00:06 UTC, GuySartorelli commented
> added lots of new inconsistently named API

How is any of it inconsistently named?

> It seems like the whole thing could be done much simpler by just move the canView() checks to GridField::getManipulatedList()

What if a manipulator _adds more items_ to the list by reducing the restrictions on filters? Or relies on `DataList` functionality such as filtering by `SearchFilter` syntax (e.g. `->filter('SomeField:StartsWith', 'some string start')`) or does any number of other things we can't predict?

While that would reduce the number of changes the PR introduces in terms of lines of code, it _drastically_ increases the number of _functional_ changes, and potential regressions.

2023-02-17 00:56 UTC, GuySartorelli commented
Spoke with Steve - will remove the global config as it's a footgun, but I'll wait for the rest of his comments before changing that.

2023-02-17 02:01 UTC, emteknetnz commented
I'm a bit concerned here that were only providing developer controlled ways of deciding where the canView() checks happen.

Enabling canView() checks before the limit operation performed by the paginator will have negligible performance issues when a new project is being developed. However years after the initial development as data grows and grows to many thousands of records that's when you'll have serious performance issues.

When your first visit a gridfield it will have no filters applied so it will run canView checks on every record on the database table, so it's essentially as bad as the poor code example I provided above

CMS editors won't have any way of addressing the performance issues. I think wonky though functional pagination is a far better problem to have than the CMS bring unresponsive (performance issues will also affect the rest of the site)

It seems like we may want a check box on the gridfield that defaults to whatever the developer set, though content editors can toggle and is saved on the Member table (or somewhere else where user settings should be stored)

This would be a pretty strange UX experience though, as the check box is essentially "slow and accurate", or "fast with weird pagination"

2023-02-17 02:18 UTC, GuySartorelli commented
> CMS editors won't have any way of addressing the performance issues

When do they ever, outside of telling a developer "Hey I am experiencing performance issues when doing x in y section"?
This is _exactly_ why this solution is developed as an opt-in solution. Developers should only ever apply this in gridfields where they _know_ the incorrect pagination is a problem, and have reasonable expectations that there will be few enough records for the performance hit to not be noticable.

Adding a "enable bad pagination" checkbox in the gridfield is just adding unnecessary UX complexity in my mind.
How do we succinctly explain "this checkbox might make your pagination incorrect, but might speed up the CMS, but only if the reason the CMS is slow at the moment for you is because pagination checks are being done after canview checks - maybe ask a developer if that's the case first, and only tick this box if you have a lot of records or complex canview checks"?

2023-02-17 02:43 UTC, michalkleiner commented
My 2 cents unrelated to the actual code change, but to the problem itself — I prefer, both as a developer and as a user, to have correct and true data presented to me, even if it's a bit slower, to incorrect or unreliably/unpredictably presented data. From that perspective, I would support Guy's change.
We don't know how many people are facing thousands or more records where there's a mix of permissions applied, maybe there are not that many. It's one of the caveats of having large sets of data in the CMS. These days it's also cheaper to throw more computing resources on problems like this. You have 10k entries and need the view to be fast? Get more CPU and RAM. I'm not saying we shouldn't be looking into optimisations wherever we can, but without fundamentally changing how we work with permissions, where we store them and how and when we evaluate them, there may not be an easy way forward.

2023-02-17 02:51 UTC, emteknetnz commented
Yeah the checkbox is would be weird. It's not a great solution, though I can't think of an actual good solution here. This is possibly just unsolvable, it's not the first time people have looked at this particular issue

As mentioned above, the performance issues won't show up until long after the initial build on a site. Even though this is an opt-in once developers know about this the temptation will just be to enable it for everything, because why not? it fixes pagination. Things will work fine for the initial build where the are 50 test records, but not so well once the tables ballooned to 20,000 records. I'm not sure it's realistic for developers to have any comprehension for how big a database table will be in 3 years time. 

I'm not really keen on a solution which isn't scalable at all. Enabling this means the CMS will get slower as you put more data into it

2023-02-17 02:57 UTC, GuySartorelli commented
Sounds like we might need a few more viewpoints to decide if this is worthwhile. @silverstripe/core-team anyone else got views on this?

2023-02-17 09:53 UTC, kinglozzer commented
I feel like this won’t get much buy-in, but throwing it out there anyway: is “don’t perform canView checks” a possible future option? Or is this too big of a footgun?

Obviously it’s better to do the filtering at a database-level if possible, so by leaving it up to developers to implement filtering when they construct the GridField we’d effectively be encouraging that. They could still call canView themselves if they wanted to use that method specifically, and I suppose we could still call canView by default in scaffolded GridFields. We don’t perform canView checks on any other form fields (optionset, dropdownfield, checkboxset etc) so there’s _some_ precedent for leaving this up to developers, though obviously GridField is quite unique. 

For this change specifically, I think this would need to be kept as opt-in if we’re introducing it in 4.x, otherwise I’m sure the upgrade will break sites for people (I can think of at least 4 we maintain off the top of my head that would _definitely_ time-out, many more that “might”). Opting in to a fix does feel weird to me, but it’s probably the best option for 4.x if we’re determined to solve this. That said, it’s not like we‘ve been inundated with bug reports about this, so I don’t think it’s vitally important we fix this _at all_ - we could just document it and move on.

2023-02-21 23:19 UTC, maxime-rainville commented
I don't think we should merge this into core ... at least not without more validation.

My suggestion would to spin this of as community module to see how much adoption it gets organically. I'd be OK with adding a few hooks to core if it's needed to make this happen.

On a related note, one idea that has been percolating in the back of my mind is to create a extension/abstraction that would allow you to define DB logic to filter a DataList by `CanView`. e.g. If you have a DataObject that is owned by a Member and only the owner has CanView rights on that DataObject, it would be pretty trivial to write a query that will only return entries that can be viewed by a specific member.

This idea and this PR could complement each other nicely.

2023-02-21 23:24 UTC, GuySartorelli commented
I don't have the time, motivation, or energy to spin this off as its own module right now. I'll just close the PR and someone else can run with it in their own module if they want.

2023-02-21 23:24 UTC, closed without merging