ENH Updated deprecation warning message
silverstripe/silverstripe-framework pull request #10709
Opened 2023-02-28 08:38 UTC by sabina-talipova

### Description
Changed version from 4.4 to 5.0.0 and updated deprecation warning message 

### Parent issue
- https://github.com/silverstripe/silverstripe-framework/issues/10609

2023-02-28 20:49 UTC, GuySartorelli requested changes

2023-02-28 20:49 UTC, GuySartorelli commented on src/ORM/Connect/MySQLDatabase.php
> +            Deprecation::notice('5.0.0', 'The $chain parameter will be removed in CMS 5');
```suggestion
            Deprecation::notice('4.4.0', 'The $chain parameter for ' . __METHOD__ . ' is deprecated', Deprecation:SCOPE_GLOBAL);
```
The old version is correct - the version should be when it was deprecated, not when it's being removed.

The new message should say what method it's in, and it shouldn't declare when it will be removed. In this case we do know it has actually been removed in CMS 5 but as a rule we have decided deprecation notices should avoid saying when the API is removed for consistency. 

Global scope is needed so we don't have a message saying the method is deprecated, since it's not the whole method that's deprecated.

2023-02-28 22:40 UTC, sabina-talipova commented on src/ORM/Connect/MySQLDatabase.php
> +            Deprecation::notice('5.0.0', 'The $chain parameter will be removed in CMS 5');
DONE

2023-03-01 01:19 UTC, GuySartorelli commented on src/ORM/Connect/MySQLDatabase.php
> +            Deprecation::notice('5.0.0', 'The $chain parameter will be removed in CMS 5');
Close enough 👌

2023-03-01 01:19 UTC, GuySartorelli approved these changes

2023-03-01 01:19 UTC, merged