NEW ORM eager loading
silverstripe/silverstripe-framework pull request #10783
Opened 2023-05-16 07:55 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-framework/issues/8426

I'm testing an alternate simpler approach to https://github.com/silverstripe/silverstripe-framework/pull/8687

2023-06-06 22:04 UTC, sabina-talipova requested changes

2023-06-06 22:04 UTC, sabina-talipova commented on src/ORM/DataObject.php
> +    private $eagerLoadedData = [];
Could we lift `private $eagerLoadedData = [];` up closer to all another class properties.

2023-06-06 22:04 UTC, sabina-talipova commented on src/ORM/DataList.php
> +        $relations = array_merge(['root'], explode('.', $eagerLoadRelation));
How do we use `'root'` relation after?

2023-06-07 02:33 UTC, emteknetnz commented on src/ORM/DataList.php
> +        $relations = array_merge(['root'], explode('.', $eagerLoadRelation));
We don't, it's basically just a placeholder so that the other array indexes are properly aligned

2023-06-07 02:58 UTC, emteknetnz commented on src/ORM/DataObject.php
> +    private $eagerLoadedData = [];
Updated

2023-06-08 00:29 UTC, sabina-talipova reviewed
Great work. While it's very difficult to determine how things work, I've tested locally with a not very large amount of data and the relationship between `many_many` and `belongs_to` and it looks like everything works well.

2023-06-08 21:52 UTC, sabina-talipova approved these changes
LGTM

2023-06-08 21:52 UTC, merged

2023-06-08 22:08 UTC, nfauchelle commented
Woah, great work this will be so helpful.
When do you think this will make release? @sabina-talipova

2023-06-08 22:44 UTC, sabina-talipova commented
Hi @nfauchelle,
This will be in the 5.1.0 release, but we haven't got a date yet. Looking forward to it :)

2023-06-08 23:24 UTC, maxime-rainville commented
@nfauchelle We're probably looking at tagging a 5.1 around October, but we're not sure yet.