FIX Duplicate page keeps original pages canView and canEdit permission
silverstripe/silverstripe-framework pull request #10806
Opened 2023-06-08 20:45 UTC by sabina-talipova

## Description
- Add property `cascade_duplicates` to SiteTree class with specified relation names to duplicate and save against the new clone object. 

## Parent issue
- https://github.com/silverstripe/silverstripe-cms/issues/2609

2023-06-09 02:42 UTC, emteknetnz requested changes

2023-06-09 02:42 UTC, emteknetnz commented on src/Security/InheritedPermissionsExtension.php
> +    private static $cascade_duplicates = [
```suggestion
    private static array $cascade_duplicates = [
```

2023-06-09 04:24 UTC, sabina-talipova commented on src/Security/InheritedPermissionsExtension.php
> +    private static $cascade_duplicates = [
Done

2023-06-12 00:44 UTC, emteknetnz approved these changes
Tested locally, works good

2023-06-12 01:29 UTC, merged