Improve dropdown rendering speed
silverstripe/silverstripe-framework pull request #10838
Opened 2023-06-26 07:59 UTC by lekoala

Fixes https://github.com/silverstripe/silverstripe-framework/issues/10174

2023-06-26 11:43 UTC, michalkleiner requested changes
Failing tests are related, please review.

Apart from that, I'm not personally sure about this change. I get that preparing the list in PHP might be faster, but with that (at a stretch) we can scrape the whole templating system and do everything in PHP.

2023-06-26 11:50 UTC, lekoala commented
@michalkleiner yes i'm not sure why the tests are failing i need to review this and see what are the tests doing

the template system is fine for simple things, but not great for loops. rendering large list of items (eg: a dropdown with country names) is quite slow. i do think there is an issue with the templating system itself, but that's clearly out of scope :-)

2023-06-26 12:04 UTC, michalkleiner commented
Saw the comment [here](https://github.com/silverstripe/silverstripe-framework/issues/10174#issuecomment-1606894809) so I got more context now. Let's see what other @silverstripe/core-team thinks about the topic.

2023-06-26 13:00 UTC, lekoala commented
@michalkleiner tests all green ;-)

2023-06-26 14:06 UTC, michalkleiner commented on src/Forms/DropdownField.php
> +    public function renderOptionsHTML(): string
Not sure here but does it need to be public? People can override the `Field` method if needed.
```suggestion
    private function renderOptionsHTML(): string
```

2023-06-26 21:50 UTC, GuySartorelli commented
I don't like this change. If there's a problem with the templating system that makes it too slow for this and similar scenarios, then resolving that problem is the fix. This feels like a project-level workaround.

I especially agree with Michal's comment: "I get that preparing the list in PHP might be faster, but with that (at a stretch) we can scrape the whole templating system and do everything in PHP."
If we start pulling template logic into PHP here, where does that end? This doesn't feel like the correct approach to the problem. I'm going to close this PR on that basis.

2023-06-26 21:50 UTC, closed without merging

2023-06-27 08:32 UTC, lekoala commented
@GuySartorelli i agree with you: i don't like this change. but when a page takes 2 times more to render because of a couple of dropdowns, that's not something that can be ignored either :-)

ideally, i think profiling should be done on the templating system and see where are the bottlenecks