FIX Resolve problems with eagerloading performance
silverstripe/silverstripe-framework pull request #10855
Opened 2023-07-04 21:51 UTC by GuySartorelli

## Issue
- https://github.com/silverstripe/silverstripe-framework/issues/10847

2023-07-04 21:53 UTC, GuySartorelli commented on src/ORM/Connect/MySQLStatement.php
> +        }
I'll extract this out into its own separate PR - this should have been part of 5.0.0 and reflects the same logic in `MySQLQuery::getIterator()` which allows the same query result (in this case the same result from `SQLSelect`) to be looped over multiple times.

2023-07-05 03:24 UTC, GuySartorelli commented on src/ORM/Connect/MySQLStatement.php
> +        }
See https://github.com/silverstripe/silverstripe-framework/issues/10856 and its associated PR.

2023-07-05 03:55 UTC, GuySartorelli commented on src/ORM/DataList.php
> +        $this->eagerLoadRelations = array_unique(array_merge($this->eagerLoadRelations, $arr));
Without this change, we'd end up processing the same set of relations twice.
For example, you added
```php
SomeClass::get()->eagerLoad(
    'MyManyMany.MyHasMany',
    'MyManyMany.MySecondHasMany',
);
```
you would have fetched `MyManyMany` for both relation chains.

2023-07-05 03:55 UTC, GuySartorelli commented on src/ORM/DataList.php
> +                $arr[] = implode('.', $usedParts);
It wasn't at all clear what was happening here - this change doesn't improve performance but it does improve code readability.

2023-07-05 03:55 UTC, GuySartorelli commented on src/ORM/DataList.php
> +            $joinRows = $joinTableQuery;
Use the query result's own iterator rather than re-inventing the wheel.

2023-07-05 03:55 UTC, GuySartorelli commented on src/ORM/DataList.php
> +            $this->eagerLoadedData[$eagerLoadRelation][$parentID][$relationName] = $arrayList;
This whole section of changes is the main performance booster and fixes the root problem in the issue.

It basically boils down to this:
- Previously we were looping through all of the join records, and for every join record we'd then loop through all of the relation records, and call `->ID` on it.
- Now we're getting the IDs up front, and the nested loop is removed entirely.

2023-07-05 03:55 UTC, GuySartorelli commented on src/ORM/DataList.php
> +            $joinThroughObjs = DataObject::get($join)->filter([$parentIDField => $parentIDs]);
Changed to be more consistent with the other `DataObject::get()` calls in the eager loading code

2023-07-05 03:55 UTC, GuySartorelli commented on src/ORM/DataList.php
> +            foreach ($query as $itemData) {
Use the query's own iterator rather than reinventing the wheel.

2023-07-06 02:13 UTC, emteknetnz commented
Just noting in my own testing with this PR that eager loading actually had a larger impact on many-many than has-many, counter to the testing in the description on this PR.  I guess it's a case of "your mileage may vary" and "you should validate whether or not eager loading works for your particular website"

2023-07-06 02:13 UTC, emteknetnz requested changes
Tested locally, seems to work great.

2023-07-06 02:13 UTC, emteknetnz commented on src/ORM/DataList.php
> +                $map[$parentID] = [];
May as well just make this an `ArrayList` at this point and not bother with the intermediary array. Performance wise it'll be no difference because `ArrayList::push()` is simply `$this->items[] = $item;`

Means further down we can just go `$this->eagerLoadedData[$eagerLoadRelation][$parentID][$relationName] = $children;`

2023-07-06 02:13 UTC, emteknetnz commented on src/ORM/DataList.php
> +        $relationArray = DataObject::get($relationDataClass)->byIDs($relationItemIDs)->map('ID', 'Me')->toArray();
Add a note in here that 'Me' returns the DataObject, or better just update the docblock on `map()` to explain what 'Me' does. I'm OK with that being done in this PR even though it's unrelated.

2023-07-06 02:33 UTC, GuySartorelli commented on src/ORM/DataList.php
> +        $relationArray = DataObject::get($relationDataClass)->byIDs($relationItemIDs)->map('ID', 'Me')->toArray();
I don't think `Map` is the place to document `Me` since that's a method in `ViewableData`. I'll add a note here instead.
Done.

2023-07-06 02:33 UTC, GuySartorelli commented on src/ORM/DataList.php
> +                $map[$parentID] = [];
Yeah good idea, that is more consistent with the way the other relations are handled - and it ends up being a little clearer to boot. Done.

2023-07-06 05:03 UTC, emteknetnz approved these changes

2023-07-06 05:04 UTC, merged