ENH Update logo
silverstripe/silverstripe-framework pull request #10922
Opened 2023-08-18 11:40 UTC by maxime-rainville

## Parent issue
- https://github.com/silverstripe/silverstripe-admin/issues/1542

2023-08-18 15:35 UTC, kinglozzer requested changes

2023-08-18 15:35 UTC, lozcalver commented on client/styles/debug.css
> +    background: url("../images/logo_small.svg") no-repeat right 3px;
I think the actual graphic is missing from this PR?

2023-08-28 11:20 UTC, maxime-rainville commented
Logo is there now. Sorry for the brain fart.

2023-08-29 03:52 UTC, emteknetnz approved these changes
Test locally, looks good

2023-08-29 03:53 UTC, merged