FIX Add extraEmptyValues to TreedropdownField
silverstripe/silverstripe-framework pull request #11044
Opened 2023-11-08 02:43 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-admin/issues/1616

2023-11-12 23:03 UTC, sabina-talipova requested changes

2023-11-12 23:03 UTC, sabina-talipova commented on src/Forms/TreeDropdownField.php
> +    public function getSchemaValidation()
Could you, please, add unit test for this method.

2023-11-13 00:03 UTC, emteknetnz commented on src/Forms/TreeDropdownField.php
> +    public function getSchemaValidation()
Done

Note - the parent card on this is a SPIKE so don't merge this just yet, need to agree with team first that we're happy with the approach before we merge anything

2023-11-13 00:45 UTC, sabina-talipova approved these changes
LGTM

2023-11-13 00:56 UTC, GuySartorelli requested changes
Overall seems okay to me - though as a bugfix that affects CMS 4 and doesn't add any new API, this should target 4.13, shouldn't it?

2023-11-26 23:58 UTC, emteknetnz commented
Closed in favor of https://github.com/silverstripe/silverstripe-framework/pull/11068

2023-11-27 00:00 UTC, closed without merging