FIX Unknown column 'ClassName' in field list
silverstripe/silverstripe-framework pull request #11127
Opened 2024-02-07 16:39 UTC by lekoala

Fixes https://github.com/silverstripe/silverstripe-framework/issues/10737

## Description

See related issue

## Manual testing steps

See related issue

## Issues

https://github.com/silverstripe/silverstripe-framework/issues/10737

## Pull request checklist

- [x] The target branch is correct
    - See [picking the right version](https://docs.silverstripe.org/en/contributing/code/#picking-the-right-version)
- [x] All commits are relevant to the purpose of the PR (e.g. no debug statements, unrelated refactoring, or arbitrary linting)
    - Small amounts of additional linting are usually okay, but if it makes it hard to concentrate on the relevant changes, ask for the unrelated changes to be reverted, and submitted as a separate PR.
- [x] The commit messages follow our [commit message guidelines](https://docs.silverstripe.org/en/contributing/code/#commit-messages)
- [x] The PR follows our [contribution guidelines](https://docs.silverstripe.org/en/contributing/code/)
- [x] Code changes follow our [coding conventions](https://docs.silverstripe.org/en/contributing/coding_conventions/)
- [] This change is covered with tests (or tests aren't necessary for this change)
- [x] Any relevant User Help/Developer documentation is updated; for impactful changes, information is added to the changelog for the intended release
- [] CI is green

2024-02-07 16:40 UTC, lekoala commented
So this is a first attempt to get the ball rolling
Ignoring the case clause is the easy way to prevent the error
it would be better to make the actual join, but that would require more analysis to know what is the relation being used in that case, not exactly sure how/when to do that

2024-02-07 22:58 UTC, michalkleiner commented on src/ORM/DataQuery.php
> +                            $collisionTable = $schema->tableForField($collisionClass, 'ClassName');
We probably shouldn't override the `$collisionTable` variable set for the whole loop, even though it's not used beyond this line, just as a good practice. Could be named e.g. `$tableForClassNameField` or `classNameFieldTable` or similar.

2024-02-08 00:24 UTC, GuySartorelli requested changes
Seems sensible - if I'm understanding this code correctly, it shouldn't introduce new potential collisions, since this table isn't being included in the table anyway and therefore couldn't collide with anything?

2024-02-08 00:24 UTC, GuySartorelli commented on src/ORM/DataQuery.php
> +                            // Only add clause if this is already joined "Unknown column 'ClassName' error"
```suggestion
                            // Only add clause if this is already joined to avoid "Unknown column 'ClassName'" error
```

2024-02-08 08:14 UTC, lekoala commented on src/ORM/DataQuery.php
> +                            $collisionTable = $schema->tableForField($collisionClass, 'ClassName');
good point, renamed the var
i missed the var above
it's actually kind of unexpected that these do not yield the same results by the way

2024-02-08 08:16 UTC, lekoala commented
> Seems sensible - if I'm understanding this code correctly, it shouldn't introduce new potential collisions, since this table isn't being included in the table anyway and therefore couldn't collide with anything?

that's the idea. it seems to work just fine in my case and the field has the right value (in my case, it's a MemberID ...)

2024-02-09 09:04 UTC, lekoala commented
any other wishes? :)

2024-02-10 08:46 UTC, michalkleiner commented
> any other wishes? :)

I'd like a trip to Bali, thanks!

2024-02-12 20:51 UTC, GuySartorelli approved these changes
Sounds like Michal is happy with this now (and ready for a vacation already 😂).
Looks good to me.

2024-02-12 20:51 UTC, merged