NEW Wire up symfony/validator
silverstripe/silverstripe-framework pull request #11123
Opened 2024-01-31 23:21 UTC by GuySartorelli

## Description

Wires up `symfony/validator` so we can use it for robust and potentially complex validation logic.

Usage is:
```php
use SilverStripe\Core\Validation\ConstraintValidator;

/**
 * @var \Symfony\Component\Validator\Constraint $constraint
 * @var \SilverStripe\ORM\ValidationResult $result
 */
$result = ConstraintValidator::validate($valueToValidate, $constraint);
```

e.g. for testing if a URL is valid:
```php
use SilverStripe\Core\Validation\ConstraintValidator;
use Symfony\Component\Validator\Constraints\Url;

$isValid = ConstraintValidator::validate($url, new Url())->isValid();
```

Most of the constraints in https://symfony.com/doc/current/reference/constraints.html are explicitly supported, except for the following:

Any which require `symfony/expression-language`:
- `Symfony\Component\Validator\Constraints\Expression`
- `Symfony\Component\Validator\Constraints\ExpressionSyntax`
- `Symfony\Component\Validator\Constraints\When`

Any which require `symfony/http-client`:
- `Symfony\Component\Validator\Constraints\NotCompromisedPassword`

Any which require `symfony/intl`:
- `Symfony\Component\Validator\Constraints\Bic`
- `Symfony\Component\Validator\Constraints\Country`
- `Symfony\Component\Validator\Constraints\Currency`
- `Symfony\Component\Validator\Constraints\Language`
- `Symfony\Component\Validator\Constraints\Locale`

Any which require `symfony/doctrine` or anything which assumes we're using symfony/validate in the context of setting constraints on metadata objects:
- `Symfony\Component\Validator\Constraints\Cascade`
- `Symfony\Component\Validator\Constraints\Traverse`
- `Symfony\Component\Validator\Constraints\Valid`

With exception of those last three (which I've mentioned in the docs are explicitly not supported, because it relies on extra wiring up of things that we just aren't gonna do), I'd expect the others to all work - I just haven't included tests for them because we don't have those dependencies.

## Issues

- https://github.com/silverstripe/silverstripe-linkfield/issues/17

## Pull request checklist

- [x] The target branch is correct
    - See [picking the right version](https://docs.silverstripe.org/en/contributing/code/#picking-the-right-version)
- [x] All commits are relevant to the purpose of the PR (e.g. no debug statements, unrelated refactoring, or arbitrary linting)
    - Small amounts of additional linting are usually okay, but if it makes it hard to concentrate on the relevant changes, ask for the unrelated changes to be reverted, and submitted as a separate PR.
- [x] The commit messages follow our [commit message guidelines](https://docs.silverstripe.org/en/contributing/code/#commit-messages)
- [x] The PR follows our [contribution guidelines](https://docs.silverstripe.org/en/contributing/code/)
- [x] Code changes follow our [coding conventions](https://docs.silverstripe.org/en/contributing/coding_conventions/)
- [x] This change is covered with tests (or tests aren't necessary for this change)
- [x] Any relevant User Help/Developer documentation is updated; for impactful changes, information is added to the changelog for the intended release
- [x] CI is green

2024-02-01 20:50 UTC, emteknetnz requested changes
Add a unit test(s) for passing in an array of contraints

Add a unit test for passing in optional field param

2024-02-01 20:50 UTC, emteknetnz commented on src/Core/Validation/ConstraintValidator.php
> +     * @param Constraint[]|Constraint $constraints a constraint or array of constraints to validate against
```suggestion
     * @param Constraint|Constraint[] $constraints a constraint or array of constraints to validate against
```

2024-02-01 22:31 UTC, GuySartorelli commented on src/Core/Validation/ConstraintValidator.php
> +     * @param Constraint[]|Constraint $constraints a constraint or array of constraints to validate against
Done

2024-02-01 22:31 UTC, GuySartorelli commented
> Add a unit test(s) for passing in an array of contraints

Done

> Add a unit test for passing in optional field param

Done

Also added an exception (and test for it) when passing in an empty array.

2024-02-02 00:15 UTC, emteknetnz approved these changes

2024-02-02 00:15 UTC, merged