Allow better subclassing of MoneyField
silverstripe/silverstripe-framework pull request #11150
Opened 2024-02-16 11:50 UTC by beerbohmdo

Move generation of NumberField from constructor to method to allow override in subclass.

## Description

## Manual testing steps

## Issues

- #

## Pull request checklist

- [ ] The target branch is correct
    - See [picking the right version](https://docs.silverstripe.org/en/contributing/code/#picking-the-right-version)
- [ ] All commits are relevant to the purpose of the PR (e.g. no debug statements, unrelated refactoring, or arbitrary linting)
    - Small amounts of additional linting are usually okay, but if it makes it hard to concentrate on the relevant changes, ask for the unrelated changes to be reverted, and submitted as a separate PR.
- [ ] The commit messages follow our [commit message guidelines](https://docs.silverstripe.org/en/contributing/code/#commit-messages)
- [ ] The PR follows our [contribution guidelines](https://docs.silverstripe.org/en/contributing/code/)
- [ ] Code changes follow our [coding conventions](https://docs.silverstripe.org/en/contributing/coding_conventions/)
- [ ] This change is covered with tests (or tests aren't necessary for this change)
- [ ] Any relevant User Help/Developer documentation is updated; for impactful changes, information is added to the changelog for the intended release
- [ ] CI is green

2024-02-16 22:54 UTC, GuySartorelli requested changes
Seems sensible. Thanks for contributing!

Couple of small changes.
If there's an existing test for `buildCurrencyField()`, please add one for the new method as well.

## your pr description
Please fill in all sections of the template, including linking to an issue.
If no issue currently exists, please create one. We track issues, not pull requests.

Please also tick all of the check boxes that apply - if you find that you can't tick a checkbox it probably means there's some more work for you to do (e.g. the commit message doesn't match the guidelines right now)

2024-02-16 22:54 UTC, GuySartorelli commented on src/Forms/MoneyField.php
> +     * @return void
```suggestion
     Builds a field to input the amount of money
```

2024-02-16 22:54 UTC, GuySartorelli commented on src/Forms/MoneyField.php
> +    protected function buildAmountField()
```suggestion
    protected function buildAmountField(): void
```

2024-02-19 13:17 UTC, beerbohmdo commented
> If there's an existing test for buildCurrencyField(), please add one for the new method as well.

There was no test for this method, I am not even sure what you wan't to test here. Nevertheless, I've added two test methods.


I will create a issue for this.

2024-02-19 20:09 UTC, GuySartorelli requested changes
Thank you for the tests, that's fantastic! Exactly what I was after.

Just a couple of small things to tidy up, then I'll be happy to merge this.

2024-02-19 20:09 UTC, GuySartorelli commented on src/Forms/MoneyField.php
> +     * @return void
Still need to remove this per the above review
```suggestion
```

2024-02-19 20:09 UTC, GuySartorelli commented on tests/php/Forms/MoneyFieldTest.php
> +    public function testCurrencyField(): void
```suggestion
    public function testGetCurrencyField(): void
```

2024-02-19 20:09 UTC, GuySartorelli commented on tests/php/Forms/MoneyFieldTest.php
> +    public function testAmountField(): void
```suggestion
    public function testGetAmountField(): void
```

2024-02-25 22:20 UTC, GuySartorelli approved these changes
Fantastic, thank you for implementing this and for your patience.

2024-02-25 22:20 UTC, merged