FIX docblock types
silverstripe/silverstripe-framework pull request #11168
Opened 2024-03-04 15:33 UTC by lekoala

## Description
Fix/improve return types for public facing apis

## Manual testing steps
Nothing, just phpstan being happy

## Issues
https://github.com/silverstripe/silverstripe-framework/issues/11149

## Pull request checklist

- [ ] The target branch is correct
    - See [picking the right version](https://docs.silverstripe.org/en/contributing/code/#picking-the-right-version)
- [ ] All commits are relevant to the purpose of the PR (e.g. no debug statements, unrelated refactoring, or arbitrary linting)
    - Small amounts of additional linting are usually okay, but if it makes it hard to concentrate on the relevant changes, ask for the unrelated changes to be reverted, and submitted as a separate PR.
- [ ] The commit messages follow our [commit message guidelines](https://docs.silverstripe.org/en/contributing/code/#commit-messages)
- [ ] The PR follows our [contribution guidelines](https://docs.silverstripe.org/en/contributing/code/)
- [ ] Code changes follow our [coding conventions](https://docs.silverstripe.org/en/contributing/coding_conventions/)
- [ ] This change is covered with tests (or tests aren't necessary for this change)
- [ ] Any relevant User Help/Developer documentation is updated; for impactful changes, information is added to the changelog for the intended release
- [ ] CI is green

2024-03-07 12:17 UTC, kinglozzer requested changes
One minor tweak, otherwise good to merge

2024-03-07 12:17 UTC, kinglozzer commented on src/Control/HTTPRequest.php
> +     * @param string $mimeType
```suggestion
     * @param string|null $mimeType
```

2024-03-07 20:41 UTC, GuySartorelli commented
Can you please tick all of the appropriate checkboxes? It's intended both as a "have I done everything I need to?" checklist for you, as well as a "Is the contributor still working on this or is it clear there is still more to do?" list for maintainers.
As it stands, with none of the boxes ticked, it looks like this isn't even ready to be reviewed.

2024-03-07 20:42 UTC, GuySartorelli commented
Please also link to an **open** issue - we can't track closed issues

2024-03-08 08:02 UTC, lekoala commented
@GuySartorelli  issue created https://github.com/silverstripe/silverstripe-framework/issues/11173

2024-03-10 20:13 UTC, GuySartorelli requested changes
LGTM, it's an all 'round incremental improvement with no discernable side effects.

Please change the commit message from `FIX` to either `MNT` or `ENH` - `FIX` is for bugs that affect code, but this doesn't affect any of the actual code.

2024-03-12 21:08 UTC, GuySartorelli commented
Ahh, I didn't notice this has a bunch of commits, so I'll have to squash merge anyway, so I can change the commit message during that process.

2024-03-12 21:08 UTC, merged