ENH Add lightweight test override for Environment::isCli()
silverstripe/silverstripe-framework pull request #11171
Opened 2024-03-06 04:06 UTC by GuySartorelli

Required for a test in https://github.com/silverstripe/silverstripe-linkfield/pull/244

## Issue
- https://github.com/silverstripe/silverstripe-linkfield/issues/228

2024-03-07 12:13 UTC, kinglozzer commented
This seems a bit odd - introducing a property with no way to change its value, then using reflection in the linked pull request. Why not add a setter for this? If it’s just for semver reasons, I’d rather we broke that convention than hacked in code like this. If we can’t, then could we introduce a `SS_FORCE_IS_CLI` environment variable instead of a property/reflection?

2024-03-07 20:08 UTC, GuySartorelli commented
> Why not add a setter for this?

This is literally only for use in unit tests. There is no valid use case for using this outside of unit tests, and by not adding a setter that sort of usage is discouraged.

A setter also becomes public API, which means we have to maintain BC for it afterward, which is not what we want for something that is only for use in testing. Same with environment variables.

2024-03-14 02:31 UTC, emteknetnz requested changes

2024-03-14 02:31 UTC, emteknetnz commented on src/Core/Environment.php
> +    private static ?bool $cliOverride = null;
```suggestion
    /**
     * Used by unit tests to override `isCli()`
     * This is not config, so use reflection to change the value
     * @internal
     */
    private static ?bool $isCliOverride = null;
```

2024-03-14 02:31 UTC, emteknetnz commented on src/Core/Environment.php
> +            return self::$cliOverride;
```suggestion
        if (self::$isCliOverride !== null) {
            return self::$isCliOverride;
```

2024-03-18 00:48 UTC, GuySartorelli commented on src/Core/Environment.php
> +    private static ?bool $cliOverride = null;
Done

2024-03-18 00:49 UTC, GuySartorelli commented on src/Core/Environment.php
> +            return self::$cliOverride;
Done

2024-03-18 00:51 UTC, GuySartorelli commented
I have added JOIN support for `SQLUpdate` so I can do an optimisation in the linkfield migration when setting the owner. Since this is targetting the next minor it's safe to do.
It also means others can now use this functionality, which is well supported in SQL and really useful.
It also will save me at least half a day trying to get kinda-gross workarounds working.

2024-03-19 22:49 UTC, emteknetnz approved these changes

2024-03-19 22:49 UTC, merged