FIX Ensure everything gets flushed when flushing from sake
silverstripe/silverstripe-framework pull request #11436
Opened 2024-10-21 21:05 UTC by GuySartorelli

Ensures `Flushable` classes get flushed when flush booting the kernel, regardless of where that's happening from.

## Issue
- https://github.com/silverstripe/silverstripe-framework/issues/11435

2024-10-21 21:05 UTC, GuySartorelli commented on src/Control/Middleware/FlushMiddleware.php
> +        if ($kernel->isFlushed()) {
That method is part of the `Kernel` interface, so no need for the old method_exists check.

2024-10-21 21:06 UTC, GuySartorelli commented on src/Control/Middleware/FlushMiddleware.php
> -use SilverStripe\Core\BaseKernel;
`BaseKernel` wasn't used anywhere in this class

2024-10-21 21:07 UTC, GuySartorelli commented on tests/php/Core/KernelTest.php
> +    public function testImplementorsAreCalled()
This is the exact test (with some code quality improvements) that used to live in `FlushMiddlewareTest`

2024-10-21 21:32 UTC, GuySartorelli commented
CI failures are identical to what's happening on the `6` branch -  see https://github.com/silverstripe/silverstripe-framework/actions/runs/11448877901/job/31853334275

2024-10-22 03:20 UTC, emteknetnz requested changes
Code is fine, though FlushMiddleware just seems pointless now, just delete it and put the following in `HTTPCacheControlMiddleware::process()`

```php
$kernel = Injector::inst()->get(Kernel::class);
if ($kernel->isFlushed()) {
  $this->disableCache(true);
}
```

And deprecate in CMS 5.4.0, changelog entry, etc

Also I don't want to merge anything else into CMS 6 until we've fixed up all the [broken builds](https://github.com/silverstripe/.github/issues/320), once that's done could you please re-run tests to confirm that things are green

2024-10-22 03:22 UTC, GuySartorelli commented
> once that's done could you please re-run tests to confirm that things are green

I assume you mean _in this PR_ specifically lol

2024-10-22 04:39 UTC, GuySartorelli commented
I was avoiding unnecessary breaking changes, because this was meant to be just a quick bugfix. I'll put this back in ready, I've got way too many things running concurrently right now to do a full breaking change PR for this.

2024-10-23 21:10 UTC, GuySartorelli commented
Updated, CMS 5 PRs incoming

2024-10-25 01:28 UTC, emteknetnz approved these changes

2024-10-25 01:28 UTC, merged