FIX eagerLoad crash with nonterminal hasOne relation
silverstripe/silverstripe-framework pull request #11483
Opened 2024-11-29 01:21 UTC by MasonD

Addresses #11470

2024-11-29 02:03 UTC, MasonD commented
Looks like the failing tests are because the number of queries is no longer as previously expected. I'd appreciate input on how what I've done here has caused extra queries.

2024-12-01 21:09 UTC, GuySartorelli commented
> Looks like the failing tests are because the number of queries is no longer as previously expected. I'd appreciate input on how what I've done here has caused extra queries.

My guess, having looked briefly at the code changes but not at the tests, is that the tests were actually _not_ correct, and chains with `has_one` weren't actually checking anything after the `has_one` portion.
I don't have time to dive into the tests right now to validate that - can you please try to check whether the new results are correct or not?

2024-12-02 00:49 UTC, MasonD commented
After investigation, the tests indeed did their job and caught a bug in my code, now fixed.

2024-12-12 23:35 UTC, MasonD commented
@GuySartorelli I did resolve the failing tests, in case you missed it. The tests were correct and I was missing out on some eager fetching because of a bug.

2024-12-12 23:45 UTC, GuySartorelli commented
Thanks yup. I saw that just haven't had a chance to come back to this yet.

2024-12-13 00:14 UTC, GuySartorelli requested changes
Looks good and seems to work as expected, thanks for taking the time to do this.

Couple of things:

1. Can you please add some unit tests? One to check that this works as expected for `HasOne.HasMany` (i.e. the intended use case) and one to check that the exception is thrown for `PolymorphicHasOne.HasMany`?
2. Can you please retarget this to the `5.3` branch? That way the patch can be released immediately rather than waiting for the April minor release.
You may need to [reset your commits](https://gist.github.com/GuySartorelli/74627843aeb75e12b777b1f44cb22d2f) after retargeting the PR.

2024-12-13 00:14 UTC, GuySartorelli commented on src/ORM/DataList.php
> +                    $polymorphicRelation = $chainToDate[count($chainToDate) - 1];
```suggestion
                    $polymorphicRelation = $chainToDate[array_key_last($chainToDate)];
```
This is a stylistic suggestion so I won't block merging if it's not done, but it is more easily readable at a glance.

2024-12-13 05:37 UTC, MasonD commented
@GuySartorelli all done!

2024-12-16 20:43 UTC, GuySartorelli approved these changes
LGTM. Note the changes in the "expected" values are a result of adding new records to the `createEagerLoadData()` method which therefore had to be traversed. No additional queries were added to the eagerloading logic itself.

2024-12-16 20:43 UTC, merged