ENH Call validate on form fields within form
silverstripe/silverstripe-framework pull request #11506
Opened 2024-12-11 02:12 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-framework/issues/10908

2024-12-11 20:45 UTC, GuySartorelli requested changes
One very tiny change

2024-12-11 20:45 UTC, GuySartorelli commented on src/Forms/Form.php
>          // Automatically pass if there is no validator, or the clicked button is exempt
```suggestion
        // Automatically pass if the clicked button is exempt
```

2024-12-11 21:08 UTC, emteknetnz commented on src/Forms/Form.php
>          // Automatically pass if there is no validator, or the clicked button is exempt
Updated

2024-12-12 04:17 UTC, GuySartorelli approved these changes
LGTM

2024-12-12 04:18 UTC, merged