FEAT support variables as second and third argument
silverstripe/silverstripe-framework pull request #11521
Opened 2024-12-30 10:04 UTC by lekoala

## Description

This PR upgrades the text collector to support collecting arguments as variables for second and third argument (see examples below).

## Manual testing steps

```php
        // Should display last $str and support concatenation
        $str = 'Should NOT appear';
        $str = 'Lazy loading can increase perceived page performance by slightly delaying media loading. ' .
            'Eager loading will load files as soon as possible and can be used if the image is in view as the page ' .
            'loads (above or near the fold).';
        $titleTipContent = _t('DemoAdmin.LoadingTitleTip', $str);

        // Does not support variables, use {type}. This will improperly detect "test" as value for the translation
        $type = "test";
        $IDontHaveAValidSyntax = _t(__CLASS__ . '.CANNOT_DELETE', "Not allowed to delete '$type' records");

        // Support variable as third argument
        $var = ['some' => 'var'];
        $IWasNotCollected = _t('DemoAdmin.ImNOTCollected', 'test {some}', $var);

        // Support default case
        $ImCollected = _t('DemoAdmin.ImCollected', 'test {some}', ['some' => 'var']);
```

## Issues
https://github.com/silverstripe/silverstripe-framework/issues/11268
https://github.com/silverstripe/silverstripe-asset-admin/issues/1532

## Pull request checklist
- [] The target branch is correct
    - See [picking the right version](https://docs.silverstripe.org/en/contributing/code/#picking-the-right-version)
- [ ] All commits are relevant to the purpose of the PR (e.g. no debug statements, unrelated refactoring, or arbitrary linting)
    - Small amounts of additional linting are usually okay, but if it makes it hard to concentrate on the relevant changes, ask for the unrelated changes to be reverted, and submitted as a separate PR.
- [ ] The commit messages follow our [commit message guidelines](https://docs.silverstripe.org/en/contributing/code/#commit-messages)
- [ ] The PR follows our [contribution guidelines](https://docs.silverstripe.org/en/contributing/code/)
- [ ] Code changes follow our [coding conventions](https://docs.silverstripe.org/en/contributing/coding_conventions/)
- [ ] This change is covered with tests (or tests aren't necessary for this change)
- [ ] Any relevant User Help/Developer documentation is updated; for impactful changes, information is added to the changelog for the intended release
- [ ] CI is green

2025-01-05 23:37 UTC, GuySartorelli commented
Please fill in the PR checklist. That checklist is there to help you as the contributor double check you've done everything you need to do. That means that I as the reviewer will then know whether you have done those things which speeds things up a little.

2025-01-06 00:08 UTC, GuySartorelli requested changes
Most of this review is just me asking for clarification, since I haven't worked in this part of the code much before so I need a bit of help understanding what's going on.

2025-01-06 00:08 UTC, GuySartorelli commented on src/i18n/TextCollection/i18nTextCollector.php
> +                if ($id === T_CONSTANT_ENCAPSED_STRING && $inVar && $text) {
Are falsy checks correct here? What if the values are an empty string or `'0'`?

2025-01-06 00:08 UTC, GuySartorelli commented on src/i18n/TextCollection/i18nTextCollector.php
> +        $inVar = null;
What is "inVar"? Does this just track "something is in a variable"?
It looks like we use it to track only the most recently encountered variable in the entire file, but only until the assignment is finished being parsed and then we stop tracking it. Is that correct?
Might warrant an inline comment.

2025-01-06 00:08 UTC, GuySartorelli commented on src/i18n/TextCollection/i18nTextCollector.php
> +                if ($text === ';') {
```suggestion
                // Stop tracking the variable as we've finished parsing its assignment
                if ($text === ';') {
```
This assumes my earlier assumption about what `$inVar` is used for is correct.

2025-01-06 00:08 UTC, GuySartorelli commented on src/i18n/TextCollection/i18nTextCollector.php
> +
```suggestion
```
Doesn't seem like there's any reason to separate these variables from the ones above.

2025-01-06 00:08 UTC, GuySartorelli commented on src/i18n/TextCollection/i18nTextCollector.php
> +        $stringVariables = [];
Are we tracking _all_ variables that contain a string in the whole file? That's probably okay given the way this parsing is done, just want to be sure I understand what's going on.

2025-01-06 00:08 UTC, GuySartorelli commented on src/i18n/TextCollection/i18nTextCollector.php
> +                // Allow _t(Entity.Key, 'translation', $var) and expand _t(Entity.Key, $var)
What part of these examples is the part being allowed? And what do you mean by "expand" the second example?

2025-01-06 00:08 UTC, GuySartorelli commented on src/i18n/TextCollection/i18nTextCollector.php
> +                    }
How does having exactly two items mean we have a translation? Are the two items the key and the default text?
And is the continue because it doesn't matter what's in any subsequent arguments to the `_t()` function?

2025-01-06 00:08 UTC, GuySartorelli commented on src/i18n/TextCollection/i18nTextCollector.php
> +                    // The variable is the second argument or present in the parameter
What is "the parameter" in this context? Does that mean it's in the third (or subsequent) argument?

2025-01-06 00:08 UTC, GuySartorelli commented on src/i18n/TextCollection/i18nTextCollector.php
> +                    // We have a translation, eg: _t(Entity.Key, 'translation', $var)
By "we have a translation" do you mean "we've fully captured this localisation key and its default text"? If so, please change the comment to something in that vain so it's clear what you mean.

2025-01-06 00:08 UTC, GuySartorelli commented on src/i18n/TextCollection/i18nTextCollector.php
> +                    // It's translated, continue
By "It's translated" do you mean "We've fully captured this localisation key and its default text"? If so, please change the comment to something in that vain so it's clear what you mean.

2025-01-06 00:08 UTC, GuySartorelli commented on src/i18n/TextCollection/i18nTextCollector.php
> +                        // Deal with ''
Does this mean "deal with empty strings" or "deal with single quotes"? OR something else?
And in either case, what scenario do we find those in? Is it in the first argument? The second? Somewhere else?

2025-01-06 00:10 UTC, GuySartorelli commented
Please retarget this to the `5` branch - it's adding new functionality and has a risk of regression that I'd rather not introduce in a patch.

2025-01-06 09:47 UTC, lekoala commented on src/i18n/TextCollection/i18nTextCollector.php
> +        $inVar = null;
inVar is how i've collected $str = 'something' before the _t call is made
this allows         $str = 'Lazy loading can increase perceived page performance by slightly delaying media loading. ' .
            'Eager loading will load files as soon as possible and can be used if the image is in view as the page ' .
            'loads (above or near the fold).';
        $titleTipContent = _t('DemoAdmin.LoadingTitleTip', $str);
to work, even when being multiple strings concatenated together

2025-01-06 09:48 UTC, lekoala commented on src/i18n/TextCollection/i18nTextCollector.php
> +                if ($id === T_CONSTANT_ENCAPSED_STRING && $inVar && $text) {
mhh an empty string doesn't matter, but indeed "0" as a translation would fail at the moment
not very likely that someone would do $str = '0' but still i guess I could improve this :)

2025-01-06 09:48 UTC, lekoala commented on src/i18n/TextCollection/i18nTextCollector.php
> +                if ($text === ';') {
yes

2025-01-06 09:49 UTC, lekoala commented on src/i18n/TextCollection/i18nTextCollector.php
> +
it's just a way to "group" them visually but i'll happily remove the extra space

2025-01-06 09:49 UTC, lekoala commented on src/i18n/TextCollection/i18nTextCollector.php
> +        $stringVariables = [];
yes, i track everything because you don't know what is going to be called later on

2025-01-06 09:51 UTC, lekoala commented on src/i18n/TextCollection/i18nTextCollector.php
> +                    }
the current entity is an array with the following entries: name, translation, comments

if count = 1 : the translation key is being defined, but no translation has been found yet
if count = 2 : a translation has been stored for this key
if count = 3 : there is a comment

to be honest it's not very intuitive and it would deserve to be refactored to something less arbitrary (some kind of structered data) but that's how it works at the moment and i didn't want to change everything

2025-01-06 09:52 UTC, lekoala commented on src/i18n/TextCollection/i18nTextCollector.php
> +                    // The variable is the second argument or present in the parameter
it's when you have _t('key', 'translation', $var) or _t('key', 'translation', 'comments' . $var) => not than this should be ever done anyway, but that can happen

2025-01-06 09:54 UTC, lekoala commented on src/i18n/TextCollection/i18nTextCollector.php
> +                    // We have a translation, eg: _t(Entity.Key, 'translation', $var)
We have a translation just means the second argument has been provided and that we can proceed

2025-01-06 09:55 UTC, lekoala commented on src/i18n/TextCollection/i18nTextCollector.php
> +                    // It's translated, continue
it's translated in this case means a translation has been provided and need to be processed. by default captured string look like 'my translation' and need to go through processString before being stored

2025-01-06 09:56 UTC, lekoala commented on src/i18n/TextCollection/i18nTextCollector.php
> +                        // Deal with ''
it means if a string was an empty string (=> '') then there is no point in storing an empty translation

2025-01-06 09:58 UTC, lekoala commented
@GuySartorelli ideally i'd like to make sure there is no regression
currently, code like this  https://github.com/silverstripe/silverstripe-asset-admin/issues/1532 is not being collected so I assume it is considered "valid code" according to current features, no?

2025-01-08 20:24 UTC, GuySartorelli commented
Any change has some chance of regression. There's no _known regressions_ this causes, but because it's code I'm unfamiliar with, there is a chance of regressions that I won't be able to identify.

Regardless, as this is adding new functionality, it is better included in a minor release rather than a patch release.

2025-01-09 16:46 UTC, lekoala commented
ok rebased!

2025-01-09 20:20 UTC, GuySartorelli commented
I won't have time to test this out myself until at least halfway through next week.
Unit tests would be great if you have time to implement them.

2025-01-10 09:59 UTC, lekoala commented
@GuySartorelli sure (that made me realize i was missing a line in my code^^)

This is on a blank install on my machine

Without cache folder already created (initial warm up, or if clearing the whole cache directory)

manifest
---
Time: 8s
Peak memory: 16.000Mb
Memory: 16.00Mb

improved_manifest
---
Time: 1s
Peak memory: 16.000Mb
Memory: 16.00Mb

With the case already in place

manifest
---
Time: 619ms
Peak memory: 6.000Mb
Memory: 6.00Mb

improved_manifest
---
Time: 417ms
Peak memory: 6.000Mb
Memory: 6.00Mb


With no surprise, creating hundreds of files on the hard drive takes a substantial amount of time on the first run. Having a in memory array also helps a lot. This comes at almost no performance cost since the whole "manifest" array end up loaded anyway, and it's larger than the file cache.

This could certainly be improved even more (i don't see the need of having a separate file cache, the whole thing could fit in the same array) and the array could be optimized to avoid storing empty entries (which is, let's face it, most of it!)

2025-01-10 13:06 UTC, lekoala commented
@GuySartorelli i added the tests and improved how i track strings. i added some comments to make it more clear how it works. the whole test suite is running fine locally

2025-01-16 20:04 UTC, GuySartorelli requested changes

2025-01-16 20:04 UTC, GuySartorelli commented on src/i18n/TextCollection/i18nTextCollector.php
> +                    // It's translated, continue
> it's translated in this case means a translation has been provided

How does text collector know there are translations provided? It shouldn't be aware of the `lang/*.yml` files.

Edit: Sounds like you've been using "translation" to refer to the default text (i.e. second argument)?

2025-01-16 20:04 UTC, GuySartorelli commented on src/i18n/TextCollection/i18nTextCollector.php
> +                // Allow _t(Entity.Key, 'translation', $var) and expand _t(Entity.Key, $var)
Please respond to these questions.

2025-01-16 20:04 UTC, GuySartorelli commented on src/i18n/TextCollection/i18nTextCollector.php
> +                    // We have a translation, eg: _t(Entity.Key, 'translation', $var)
The second argument isn't a translation, it's just the default text to display. Please update the comment to say something like "We have found the default text for this key"

2025-01-16 20:04 UTC, GuySartorelli commented on src/i18n/TextCollection/i18nTextCollector.php
> +                    // The variable is the second argument or present in the parameter
So you mean it's the third argument (or after the second argument - I guess maybe you mean it could be in the third or later argument?)? If so please change the comment to specify that.

2025-01-16 20:04 UTC, GuySartorelli commented on src/i18n/TextCollection/i18nTextCollector.php
> +        $inVar = null;
```suggestion
        $inVar = null; // Tracks the value currently being assigned to a variable
```
As per https://github.com/silverstripe/silverstripe-framework/pull/11521#discussion_r1903932492
Have I understood that correctly? If not please adjust the comment so it's appropriately indicating the purpose of this variable.

2025-01-16 20:04 UTC, GuySartorelli commented on src/i18n/TextCollection/i18nTextCollector.php
> +        $inVar = null;
Does it correctly work for adding to a variable later? e.g.
```php
$x = 'some value';
$x .= ' and some more text';
```

2025-01-16 20:04 UTC, GuySartorelli commented on src/i18n/TextCollection/i18nTextCollector.php
> +                    }
Okay. My main confusion was with the word "translation" - this isn't a translation, it's just some default text with a key. Translations come separately.

2025-01-16 20:04 UTC, GuySartorelli commented on src/i18n/TextCollection/i18nTextCollector.php
> +                    if ($id === T_CONSTANT_ENCAPSED_STRING && $inVar && $text) {
```suggestion
                    if ($id === T_CONSTANT_ENCAPSED_STRING && $inVar !== null && $text !== null) {
```
As per https://github.com/silverstripe/silverstripe-framework/pull/11521#discussion_r1903933994

2025-01-17 09:45 UTC, lekoala commented on src/i18n/TextCollection/i18nTextCollector.php
> +                    // We have a translation, eg: _t(Entity.Key, 'translation', $var)
done

2025-01-17 09:47 UTC, lekoala commented on src/i18n/TextCollection/i18nTextCollector.php
> +                    // It's translated, continue
yes indeed, i've updated the comments

2025-01-17 09:50 UTC, lekoala commented on src/i18n/TextCollection/i18nTextCollector.php
> +        $inVar = null;
it's not tracking the value, it's tracking the name of the variable. the value is stored in inVarText. i've added comments to reflect this

2025-01-17 09:50 UTC, lekoala commented on src/i18n/TextCollection/i18nTextCollector.php
> +                    if ($id === T_CONSTANT_ENCAPSED_STRING && $inVar && $text) {
perfect

2025-01-17 11:03 UTC, lekoala commented
@GuySartorelli updated the code and added test cases for falsy values and $x = 'test' ; $x .= 'more';

2025-01-17 11:04 UTC, lekoala commented on src/i18n/TextCollection/i18nTextCollector.php
> +                    // The variable is the second argument or present in the parameter
i'm not sure how to phrase that correctly :-)

2025-01-17 11:05 UTC, lekoala commented on src/i18n/TextCollection/i18nTextCollector.php
> +                if ($id === T_CONSTANT_ENCAPSED_STRING && $inVar && $text) {
updated

2025-01-27 02:31 UTC, GuySartorelli commented on src/i18n/TextCollection/i18nTextCollector.php
> +                    // The variable is the second argument or present in the parameter
Reading again I think it's probably fine as is

2025-01-27 02:31 UTC, GuySartorelli commented on src/i18n/TextCollection/i18nTextCollector.php
> +                // Allow _t(Entity.Key, 'translation', $var) and expand _t(Entity.Key, $var)
Nevermind

2025-01-27 02:32 UTC, GuySartorelli approved these changes
Looks good, great unit test. Thank you!

2025-01-27 02:32 UTC, merged