BUG Fix wrong regex matching in case of multiple </head> (#9662)
silverstripe/silverstripe-framework pull request #9664
Opened 2020-08-28 22:51 UTC by spekulatius

Hey,

Currently any page with multiple times the string "</head>" (which shouldn't exist, but do in some edge cases) end up with multiple JS requirements being inserted. This can lead to broken markup (see #9662).

This fix adds a negative lookahead in the regex matching the head-tag. It avoids multi-matching of "</head>" by limiting it the last match. As a result, the JS requirements will only be added once before the last closing head-tag. 

This fix resolved #9662.

Before merging it would be great if someone could test this further - I don't want to break stuff for many people!

Cheers,
Peter

2020-08-29 01:49 UTC, sminnee requested changes
This fix works if your head contains unescaped </head> content in JSON or similar. But what if your _body_ contains an unescaped </head>? Then this code won't work.

Perhaps the better fix here is to check if more than one </head> exists, and if so switch to a replacement approach that uses DOMDocument to parse the HTML correctly.

If that's put in place, it would be useful for insertScriptsAtBottom as well.

In any case, we should update RequirementsTest to add a test for the cases being fixed.

2020-08-29 08:08 UTC, spekulatius commented
Hey @sminnee 

good points, an unescaped head in the body is something that it definitely wouldn't work for. I'll see how to improve it.

Cheers,
Peter

2020-08-29 10:12 UTC, sminnee commented
It might be worth looking into whether the social module is escaping its content properly.

2020-08-29 10:44 UTC, spekulatius commented
@xini would you happen to know if there is any escaping done on the plain string you get?

2020-09-03 08:38 UTC, spekulatius commented
Hey @sminnee 

I guess this is strong edge case and probably won't cause any trouble in the near future. Feels like it's barely worth investing more time into it. Lets close this it for now.

Cheers!

2020-09-03 08:38 UTC, closed without merging