FIX Set action button state on form validation fail
silverstripe/silverstripe-framework pull request #9703
Opened 2020-09-22 01:39 UTC by emteknetnz

Fix for https://github.com/silverstripe/silverstripe-admin/issues/1110

2020-09-22 03:05 UTC, emteknetnz commented
The following classes can be used to manually test the button states

```php
**MultiTabPage.php**

<?php

namespace {

    use SilverStripe\CMS\Model\SiteTree;
    use SilverStripe\Forms\RequiredFields;
    use SilverStripe\Forms\TextField;
    use SilverStripe\ORM\ValidationResult;

    class MultiTabPage extends SiteTree
    {
        private static $db = [
            'SecondTabFirstField' => 'Varchar(50)',
            'ThirdTabFirstField' => 'Varchar(50)',
            'ThirdTabSecondField' => 'Varchar(50)',
            'FourthTabFirstField' => 'Varchar(50)',
            'SettingsTabFirstField' => 'Varchar(50)',
        ];

        private static $has_one = [];

        public function getCMSFields()
        {
            $fields = parent::getCMSFields();
            $fields->addFieldToTab("Root.Second", TextField::create("SecondTabFirstField"));
            $fields->addFieldToTab("Root.Third", TextField::create("ThirdTabFirstField"));
            $fields->addFieldToTab("Root.Third", TextField::create("ThirdTabSecondField"));
            $fields->addFieldToTab("Root.Fourth", TextField::create("FourthTabFirstField"));
            return $fields;
        }

        public function getSettingsFields()
        {
            $fields = parent::getSettingsFields();
            $fields->addFieldToTab("Root.Settings", TextField::create('SettingsTabFirstField'));
            return $fields;
        }

        public function getCMSValidator()
        {
            return new RequiredFields([
//                'ThirdTabFirstField', // uncomment these lines to test getCMSValidator()
//                'FourthTabFirstField',
//                'SettingsTabFirstField'
            ]);
        }

        public function validate()
        {
            $result = parent::validate();
            // $result->addError("invalid form"); // uncomment this line to test validate()
            return $result;
        }
    }
}


**MyDataObject.php**

<?php

use SilverStripe\Forms\RequiredFields;
use SilverStripe\Forms\TextField;
use SilverStripe\ORM\DataObject;
use SilverStripe\Versioned\Versioned;

class MyDataObject extends DataObject
{
    private static $extensions = [
        Versioned::class
    ];

    private static $db = [
        'MainTabFirstField' => 'Varchar(50)',
        'SecondTabFirstField' => 'Varchar(50)',
        'ThirdTabFirstField' => 'Varchar(50)',
        'ThirdTabSecondField' => 'Varchar(50)',
        'FourthTabFirstField' => 'Varchar(50)',
    ];

    public function getCMSFields()
    {
        $fields = parent::getCMSFields();
        $fields->addFieldToTab("Root.Main", TextField::create("MainTabFirstField"));
        $fields->addFieldToTab("Root.Second", TextField::create("SecondTabFirstField"));
        return $fields;
    }

    public function getCMSValidator()
    {
        return new RequiredFields([
//            'ThirdTabFirstField', // uncomment these lines to test getCMSValidator()
//            'FourthTabFirstField',
        ]);
    }

    public function validate()
    {
        $result = parent::validate();
        // $result->addError("invalid dataobject"); // uncomment this line to test validate()
        return $result;
    }
}

**MyModelAdmin.php**

<?php

use SilverStripe\Admin\ModelAdmin;

class MyModelAdmin extends ModelAdmin
{
    private static $url_segment = 'my-model-admin';

    private static $managed_models = [
        'MyDataObject'
    ];
}

```

2020-09-29 01:36 UTC, Cheddam requested changes
To me, the base `Form` class seems like the wrong place for this code. I get that you're trying to position it to be applied to multiple areas of the CMS, but this will result in API pollution / needless overhead for other uses of `Form`, including unversioned CMS UIs and front-end forms.

Digging around, it looks like the action logic might belong in two places:

- `SiteTree::getCMSActions()`
- `VersionedGridFieldItemRequest::addVersionedButtons()`

The difficult part is retrieving the validation state within those methods. One possible solution could be to add a flag to the record or form to denote when it has failed validation during the request.

Have another crack at it, and maybe have a chat to the team if you're still not sure.

2020-09-30 22:53 UTC, emteknetnz commented
@Cheddam 
I've made a crack at it though it seems like we're pretty limited by existing architecture.  I cannot see a clean solution here.  I'll outline the lay of the land below include what the problems are, and I've included an alternative solution at the end.

Apologies for my rambling communication style in advance.

When POSTING form values, thing happen in this order on the server for both SiteTree and DataObject:
1) Create a $form
2) Add $formActions (save button, publish button) to the $form
3) Create a FormRequestHandler($form) .. $this->form = $form
4) Do validation in FormRequestHandler::httpSubmission

My original solution added a 5th step after validation FormRequestHandler::httpSubmission 
5) Update the button state via $this->form->setActionButtonState().  $this->form naturally has access to $this->form->FormActions

We must do something in FormRequestHandler::httpSubmission since that's where validation happens.  So it seems like what we want to do is move the update button state logic out of Form to somewhere else.

#### SiteTree
We could create a new method SiteTree which is a bit more coupled together as CMS Actions are created there via SiteTree::getCMSActions().  So for instace we could:

SiteTree::setActionButtonState($action, $state)
{
    $this->getCMSActions() ... fieldByName('MajorActions') ... update button classes
}

FormRequestHandler::httpSubmission

if (!$result->isValid()) {
    $this->form->getRecord()->setActionButtonState('save', 'dirty')
    ...

#### DataObject / ModelAdmin
We run into problems on DataObjects because they work in a different way to SiteTree.  They are less coupled together.  There IS a DataObject::getCMSActions, but it's not used in ModelAdmin.

Instead what's used to create the FormAction buttons is GridFieldDetailForm_ItemRequest::ItemEditForm.  If the DataObject is versioned then this may be later updated with VersionedGridFieldItemRequest::addVersionedButtons.

 GridFieldDetailForm_ItemRequest::ItemEditForm is an endpoint i.e. GridFieldDetailForm_ItemRequest::$allowed_actions = [ ..., 'ItemEditForm' ]

function ItemEditForm() {
    ...
    $actions = $this->getFormActions() // << Save button created in here
    $form = new Form(..., $actions, ...) 
    return $form;
}

To reiterate, this $form is later consumed by FormRequestHandler

FormRequestHandler::__construct(Form $form) {
    $this->form = $form;
}

So, when you get to FormRequestHandler::httpSubmission, which happens AFTER Form creation, unlike with SiteTree, on DataObject there's no way to get back to the thing that created the FormActions i.e. DataObject::getCMSActions()->count() == 0, unlike SiteTree::getCMSActions()->count() == 2;

Another way to put this, DataObject::setActionButtonState($action, $state) isn't feasible because the FormActions don't live on DataObject.  SiteTree is different because FormActions DO live on SiteTree.

So the best we could do to keep the update button state logic in the same place that created it is to create a static method on GridFieldDetailForm_ItemRequest

public static function setActionButtonState(FieldList $actions)
{
    // update buttons classes
}

We'd also need to do duplicate code on VersionedGridFieldItemRequest for the publish button

We'll end up with this:

#### Alternative soltuion

FormRequestHandler::httpSubmission

```
if (!$result->isValid()) {
    $form = $this->form;
    $record = $form->getRecord();
    if (class_exists(SiteTree::class) && $record instanceof SiteTree) {
        $record->setActionButtonState('save', 'dirty');
        $record->setActionButtonState('publish', 'dirty');
    } else {
        $actions = $form->Actions();
        GridFieldDetailForm_ItemRequest::setActionButtonState($form, 'save', 'dirty');
        if ($record->hasExtension(Versioned::class)) {
            VersionedGridFieldItemRequest::setActionButtonState($form, 'publish', 'dirty');
        }
    }
```

+ 3 basically duplicate setActionButtonState() functions on various classes

It's ugly.  As I originally noted in the description that hardcoded button classes are [used all over the place](https://github.com/silverstripe/silverstripe-admin/issues/1110#issuecomment-695867148) which is a symptom of Form architecture that grew organically over time.

So do you want the alternative solution or just keep it on Form?

2020-10-02 00:13 UTC, ScopeyNZ commented
To me, the idea of setting button state like this is wrong. The form should be "dirty", not the buttons. You could add an `isDirty` API to the form, set it to dirty when hydrating it from the request, and then set it to pristine again after the validation. Ideally there would be some assertion that the generated response is 2xx, but it might be a bit difficult.

I don't think "we have bad code all over the place already" should ever be a reason to add more bad code btw. Ideally we remove all presentational concerns from our model/controller CMS code, and this isn't helping. An `isDirty` API would be fine in that regard though, as it's a state management concern, not a presentational one.

2020-10-02 06:15 UTC, Cheddam commented
I've thought about this more, and I'm at the point where I'm pretty sure this is unreasonably difficult to fix properly in the PJAX architecture.

We've been trying to tackle the leading visual bug - that the 'Save' and 'Publish' actions don't reflect the state of the form when it contains a validation error - but the real issue is that they _do_ reflect the state of the form. The change tracker that determines this state relies on there being a difference between the **remote** (original) value of each field, and the **local** (current) value. Once the form is submitted, regardless of what the validation outcome is, the **local** state _becomes_ the **remote** state, as the entire form is replaced in the DOM. This seems to be a change introduced in CMS 4 to enable field-level validation messages, as in my testing validation errors in CMS 3 simply pop a toast without replacing the form.

I was exploring the possibility of storing the 'dirty' status on the client and reapplying it to the replacement form, but this still results in broken change detection on fields. What really needs to change is that the **remote** (saved) value of the fields must be exposed separately from the **client** value, so that these values can be consistently diffed by the change tracker. This could be achieved through populating a `data-original-value` attribute on each field, but it'd be a pretty significant change with plenty of risk for breakage.

Handling this situation is pretty much par for the course in a modern AJAX form architecture - generally the API returns an `HTTP 400` response with structured data on which fields have errors, and the client simply retains its local state - but in our current PJAX architecture, it's a lot harder to solve.

This feels like a heck of an undertaking to repair the UX in an architecture we want to move away from, and this bug has seemingly existed since we introduced field-level validation, so I'm not sure how we should proceed at this stage.

cc/ @brynwhyman

2020-10-02 07:17 UTC, emteknetnz commented
>> This seems to be a change introduced in CMS 4 to enable field-level validation messages

The current architecture is to render some new `<form>` HTML on the server complete with error messages and buttons ...

>>fix properly

To me it seems like the "proper fix" given the current architecture would be to set the button state on the server when the new `<form>` is created then yeah?  Which is what has been provided in this PR, twice.  Once on Form, and secondly as an alternative solution on some different classes.

Why are we fighting against this?

Like it's no secret that the current architecture isn't ideal in some places.  However I don't think "Architecture bad, let's look to refactor everything" when someone does a simple bugfix that fits with the current architecture is the most optimal way to get bugfixes shipped to customers.

2020-10-04 04:54 UTC, Cheddam commented
I'm pushing back here because this doesn't actually fix the underlying problem, it just makes it look like it has. Even if this gets merged, we'll just end up having to raise another issue to address the real limitation, which is that the value of fields returned by the server is considered the saved value by the client, whether or not it actually reflects what's in the database.

To be clear, I'm not suggesting the only path forward is a rewrite, though I'll concede that "I think this is unreasonably difficult to fix properly in the PJAX architecture" makes it sound that way - blame my frustration after digging into this for multiple hours. I just want the decision we make on how (and whether) we proceed with this fix to be well informed and considered in the context of our future plans for the framework.

Another path to resolution within the current architecture might be to persist the original field values on the client and feed them back into the changetracker in the case of a validation error, otherwise updating them in the case of a successful save. This would likely require modifying the changetracker library, but would avoid modifying the output of forms in the backend, which is part of what made the prospect of fixing this properly in the current architecture so spooky to me in the first place.

2020-10-04 23:47 UTC, ScopeyNZ commented
Am I missing something here? The server knows both the posted and saved values in each field. Can't the server return the form hydrated with the posted values, and just indicate somehow that the form is dirty? The client can then rely on this "dirty" flag when applying the PJAX change?

2020-10-05 00:21 UTC, Cheddam commented
@ScopeyNZ The change tracker needs to know _what_ is dirty, though, and what the saved values are - otherwise it can't operate correctly. Right now it loses all context when the form is returned, whether successfully saved or not, and blindly assumes that the values returned are the saved ones.

We've had a further discussion offline on how to go forward with resolving this issue, and based on that I'm going to close this PR out, as there's no clean way to ship this partial fix. I've raised a spike to take a more holistic look at this and see if we can address some similar issues impacting Elemental too: https://github.com/silverstripe/silverstripe-admin/issues/1131

2020-10-05 00:21 UTC, closed without merging