DOC Add provisional 4.7.0 changelog
silverstripe/silverstripe-framework pull request #9729
Opened 2020-10-09 03:38 UTC by Cheddam

PHP 8 support isn't quite done (follow #9704 for progress) but we're actively working on it and can pull it out of the doc if it doesn't land in time.

2020-10-09 04:00 UTC, dnsl48 approved these changes
LGTM. Left one note

2020-10-09 04:16 UTC, Cheddam commented on docs/en/04_Changelogs/4.7.0.md
> +This change will not affect existing projects, but developers are encouraged to adopt this collation
Good call - added my compatibility notes from the original issue.

2020-10-09 05:08 UTC, sminnee requested changes
Looking good! Suggested a few improvements.

2020-10-09 05:08 UTC, sminnee commented on docs/en/04_Changelogs/4.7.0.md
> +currently supported. A future release will adopt the current mainline version of PHPUnit.
"We hope to give you better support for choosing your own testing tools, including never versions of PHPUnit, in a future release."

2020-10-09 05:08 UTC, sminnee commented on docs/en/04_Changelogs/4.7.0.md
> +
Note also that the Silverstripe dependencies don't all claim support for PHP 8, so you will need to run composer with --ignore-platform-reqs at this stage.

2020-10-09 05:08 UTC, sminnee commented on docs/en/04_Changelogs/4.7.0.md
> +affected strings in quotes.
If you wish to keep using the old Yaml parser, run "composer require symfony/yaml:^3" on your project to prevent installation of version 4.

2020-10-11 23:02 UTC, sminnee approved these changes

2020-10-12 00:03 UTC, merged