ENH - Ping function returns an HTTPResponse instead of an int
silverstripe/silverstripe-framework pull request #9745
Opened 2020-10-24 21:12 UTC by emteknetnz

Discussion https://github.com/silverstripe/silverstripe-framework/pull/9744#issuecomment-715626767

`ping` is an `$allowed_actions` in `class Security extends Controller`

The ping function has no strict types including docblocks, so in theory it's OK to change the return type from `int` to `HTTPResponse`.

![image](https://user-images.githubusercontent.com/4809037/97093639-32f37700-16aa-11eb-96db-781a4687bc91.png)

Given that it's an endpoint it should probably have been this way to begin with

2020-10-26 01:58 UTC, robbieaverill commented
I don't think that's true, introducing a return type to an existing method is a breaking change

2020-10-26 08:44 UTC, dhensby commented
What dependencies are there in this being an int instead of a http resonse or even a controller. All the internal logic of request handling should be able to deal with any of those return types, but is it possible some other code could rely on the integer type, here?

2020-10-26 08:45 UTC, dhensby requested changes

2020-10-26 08:45 UTC, dhensby commented on src/Security/Security.php
> +        return HTTPResponse::create()->setBody('1');
This isn't the right way to return a `HTTPResonse` object from a controller, really.

The response object already exists and is available through `$this->getResponse()` on any controller.

2020-10-26 19:12 UTC, emteknetnz commented
>> I don't think that's true, introducing a return type to an existing method is a breaking change

End of discussion really :-)

I'm not too attached to this so happy to just close this one.

2020-10-26 19:12 UTC, closed without merging

2020-10-27 07:49 UTC, sminnee commented
This method isn't designed to be used outside of the controller system; calling it directly and expecting an int is not part of the public API IMO.

2020-10-27 09:42 UTC, emteknetnz commented
@sminnee I agree, you could make the case that there's currently no defined return type on the function so it's actual return type is currently `mixed` not `int` so changing the return type here is valid.

I'm honestly no too fussed here since the CMS is currently not broken so this is very low impact.  It's just a nice to have.  If you feel it should be re-opened then feel free to and I'll look to get it merged.

2020-10-28 07:05 UTC, sminnee commented
A more low impact change would be to return a string "1" rather than in. The return type of these methods isn't supposed to be an int (which tripped up PHP8 afaik), so that would be a bugfix rather than an API change.