API Add a CREATE_MEMORY_HYDRATED option to DataObject constructor
silverstripe/silverstripe-framework pull request #9767
Opened 2020-11-12 03:31 UTC by maxime-rainville

This adds a fourth option to the DataObject constructor to hydrate from memory.

Fixes https://github.com/silverstripe/silverstripe-framework/issues/9750

2020-11-12 03:41 UTC, madmatt commented on src/ORM/DataObject.php
> +     * to initialised a record that doesn't yet have an ID. Neither setters and nor default population will be called.
Sentence could be structured a bit more clearly - e.g. `Setter methods are not called, and population via private static $defaults will not occur`.

2020-11-12 03:42 UTC, madmatt commented on src/ORM/DataObject.php
> +     *   DataObject::CREATE_MEMORY_HYDRATED or DataObject::CREATE_SINGLETON. Used by Silverstripe internals as best
The first occurrence of `as` should be `and` here.

2020-11-12 21:25 UTC, maxime-rainville commented on tests/php/ORM/DataObjectTest.php
> +        $this->assertNotEmpty($changedDO->ID, );
```suggestion
        $this->assertNotEmpty(
            $changedDO->ID,
            'An ID has been generated for the new class instance on save'
        );
```

2020-11-16 04:24 UTC, maxime-rainville commented
This didn't make the cut off for the 4.7 release. We're thinking we might be able to call it a bug fix since it's technically not a an API change. This would allow us to ship it in 4.7.1. We'll sort it out, once 4.7.0 stable is out the door.

2020-12-20 23:27 UTC, emteknetnz requested changes
There's a lot of duplicated code between the regular hydration and the memory hydration. If we do a bugfix sometime in the future on one of them we might forget to fix the other one. Should create a private method with shared code.

2020-12-21 02:09 UTC, sminnee commented
Or use have both options branch to the same case block, and do a further conditional/ternary inside that for the 1 difference.

2021-01-18 03:31 UTC, maxime-rainville commented
Addressed @emteknetnz's feedback. I moved the hydration logic into a private `hydrate` method with a flag that account for the difference between CREATE_HYDRATED and CREATE_MEMORY_HYDRATED.

2021-01-21 01:07 UTC, merged

2021-03-22 05:47 UTC, KhushbuFuletra commented
Hi, I am waiting for this one. 
when do you think you will be able to tag this PR?

2021-04-06 08:50 UTC, KhushbuFuletra commented
> It's going to be in the 4.8.0 release which is still a couple months away.

Thanks, @maxime-rainville  for the heads-up.