Bug Fix - Ensure DataQuery::exists() SQL is both valid MySQL and T-SQL
silverstripe/silverstripe-framework pull request #9845
Opened 2021-02-08 17:49 UTC by HARVS1789UK

The original SQL statement for checking at the DB level if a DataQuery result set has any rows (implemented in #8915) is not valid T-SQL for use with SQL Server.

This pull request aims to tweak that SQL so that it is valid MySQL **and** T-SQL. 

Note that I am not familiar with any other supported DB backends such as SQLite or PostgreSQL so someone with knowledge of these should review this change for compatibility with those please

I have made a more detailed reference to the errors this fixes in #9809

2021-02-08 19:58 UTC, ScopeyNZ approved these changes
This is changing the selected value from a boolean to an integer on PostgreSQL, but it's probably fine as we're checking for `1` in the following condition. 

Should work on Postgres (although I haven't tested it) - it only hurts my dev heart a little to see us using ints instead of booleans for a binary value.

2021-02-08 20:01 UTC, xini requested changes
the return statement can then be simplified I believe?

```
return (((int) $result) === 1);
```

2021-02-08 20:07 UTC, ScopeyNZ commented
You have to be careful as PostgreSQL can return `'f'` and `'t'`. `(int) 't' === 1` is `false`.

You could write `return $result === 't' || (int) $result === 1` though.

2021-02-08 20:27 UTC, HARVS1789UK commented
@ScopeyNZ (@xini FYI)

Re: "using int rather than boolean for a binary value" - Perhaps I am misinterpreting what you mean, but I have tried replacing 1/0 in the SQL statement with true/false instead but that throws "Invalid column name 'true'" in T-SQL and although it doesn't error in MySQL, the boolean based return values are converted to Int in the resulting output anyway.

Re: making the return statement more succinct, as well as your suggestion, this would also do the trick I suspect:
`return (!empty($result) && $result !== 'f');`

I won't weigh in on the PostgreSQL comments on 't'/'f' vs 1/0 as I have no experience with PostgreSQL

2021-02-08 21:03 UTC, ScopeyNZ commented
Your PR is fine imo. FYI Postgres has a native boolean type, which is why it's often the odd one out here. TSQL and MySQL don't - but I know that MySQL has some `tinyint(1)` support which mimics it a little. Can't speak for TSQL.

2021-02-09 08:48 UTC, sminnee commented
I believe this should be fine - note that our Boolean types use a 1-bit integer for PostgreSQL as well to keep a bit more cross-database consistency, so a 1/0 here is fine too IMO.

2021-02-09 08:50 UTC, sminnee approved these changes

2021-02-09 10:26 UTC, HARVS1789UK commented
@sminnee does your latest comment support @xini 's proposal to simplify the return statement to `return (((int) $result) === 1);` then?

2/3 of you have approved these changes, Xini's feedback is still marked as 'requesting changes' of the above, which I am happy to do if we are all in agreement that it is suitable?

Either way if/when that additional change is made and approved, what are the next steps here, all I have an option for is 'Close pull request', should I do that once approval is reached as the creator to confirm it is finished, or is that something one of the three of you do once unanimous approval has been given? (I am not a frequent contributor, bit hazy on the process)

2021-02-10 16:25 UTC, HARVS1789UK commented
Bump ☝️ 

What needs to be done for this to be merged in?

2021-02-10 18:21 UTC, merged

2021-02-10 18:21 UTC, ScopeyNZ commented
I just need to press the button 🙂