prevent spaces in emails
silverstripe/silverstripe-framework pull request #9887
Opened 2021-03-19 09:11 UTC by lekoala

so this is not the first time a customer of mine is just copy pasting stuff in emails fields and somehow, a space at the end skips validation. this update ensure there is no space before or after the email, it would probably save a lot of time for everyone to have this build in.
it's probably better to fix it here rather than at form level because this also happens for csv imports etc

2021-03-22 00:22 UTC, emteknetnz requested changes
This seems like a good thing to do.  Couple of changes to make before merging.

Could you also add the following unit test:

tests/php/Security/MemberTest.php

```php
public function testEmailIsTrimmed()
    {
        $member = new Member();
        $member->Email = " trimmed@test.com\r\n";
        $member->write();
        $this->assertNotNull(Member::get()->find('Email', 'trimmed@test.com'));
    }
```

I've validated that this will fail without your code, and pass with your code

2021-03-22 00:22 UTC, emteknetnz commented on src/Security/Member.php
> +        if($this->Email) {
```suggestion
        if ($this->Email) {
```
Fixes PHPCS error https://travis-ci.com/github/silverstripe/silverstripe-framework/jobs/492253708

2021-03-22 00:22 UTC, emteknetnz commented on src/Security/Member.php
> +        // Prevent spaces in emails
```suggestion
        // Remove any line-break or space characters accidentally added during a copy-paste operation
```

2021-03-22 08:05 UTC, lekoala commented
@emteknetnz sounds great! i made the changes

2021-04-24 09:05 UTC, Cheddam approved these changes

2021-04-24 09:05 UTC, merged