ENH Update keep me signed in tooltip text
silverstripe/silverstripe-framework pull request #9918
Opened 2021-04-15 04:54 UTC by emteknetnz

https://github.com/silverstripe/silverstripe-login-forms/issues/90

2021-04-22 22:13 UTC, maxime-rainville requested changes
Not clear why we are targeting this fix to 4.7.

2021-04-22 22:13 UTC, maxime-rainville commented on lang/en.yml
> +    REMEMBER_ME: 'Keep me signed in for {count} days'
I thought we said we weren't going to update translation string any more?

2021-04-22 22:25 UTC, emteknetnz commented on lang/en.yml
> +    REMEMBER_ME: 'Keep me signed in for {count} days'
Ug. Er, I don't think that was agreed. 

Last I got to was here - https://github.com/silverstripeltd/product-issues/issues/361#issuecomment-816279940

I think our process should probably be flexible enough to allow us to update text :-)

Leaving transifix woes aside, this text change is only a tweak which means roughly the same thing.  It's not repurposing an existing key for something else, so I think it's correct?  Means we don't automatically loose foreign translations.  So it seems correct to use the same key?

2021-04-22 22:27 UTC, emteknetnz commented
>> Not clear why we are targeting this fix to 4.7.

There's no API change, so it can be patch released

2021-04-22 22:36 UTC, maxime-rainville commented on lang/en.yml
> +    REMEMBER_ME: 'Keep me signed in for {count} days'
If you update an existing translation string, it invalidate all translation attach to that string ... even if you keep the same key.

2021-04-22 22:51 UTC, emteknetnz commented on lang/en.yml
> +    REMEMBER_ME: 'Keep me signed in for {count} days'
ノ(;Ĺ̯̿̿ ;ノ)

2021-04-23 04:41 UTC, maxime-rainville commented
Patch releases are normally bugfixes only. So it goes a bit beyond no new API.

We haven't interpreted it to be a hard rule in the past, so I'm OKish with tweaking translations. But generally people should't expect to see new UIs and new words in a patch release.

2021-04-26 22:57 UTC, emteknetnz commented on lang/en.yml
> +    REMEMBER_ME: 'Keep me signed in for {count} days'
In this particularly instance, the modified translation keys haven't actually been released / tx pushed yet, so it's OK to modify in this particular PRs

2021-04-27 22:26 UTC, merged

2021-04-28 03:00 UTC, brynwhyman commented
If it's possible to treat a UI change as a bug fix, then this is a bug fix. As per the parent issue title, changes that were previously introduced to 4.7 included "Inaccurate help text".